package org.csnowfox.maven.plugin.example.dao.fund;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.csnowfox.maven.plugin.example.dao.fund.FundCalendar;
import org.csnowfox.maven.plugin.example.dao.fund.FundCalendarExample.Criteria;
import org.csnowfox.maven.plugin.example.dao.fund.FundCalendarExample.Criterion;
import org.csnowfox.maven.plugin.example.dao.fund.FundCalendarExample;

public class FundCalendarSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public String countByExample(FundCalendarExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("FUND_CALENDAR");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public String deleteByExample(FundCalendarExample example) {
        BEGIN();
        DELETE_FROM("FUND_CALENDAR");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public String insertSelective(FundCalendar record) {
        BEGIN();
        INSERT_INTO("FUND_CALENDAR");

        if (record.getTaid() != null) {
            VALUES("taid", "#{taid,jdbcType=VARCHAR}");
        }
        if (record.getFundcode() != null) {
            VALUES("fundcode", "#{fundcode,jdbcType=VARCHAR}");
        }
        if (record.getIdate() != null) {
            VALUES("idate", "#{idate,jdbcType=VARCHAR}");
        }
        if (record.getMarketflag() != null) {
            VALUES("marketflag", "#{marketflag,jdbcType=VARCHAR}");
        }
        if (record.getUpdatetime() != null) {
            VALUES("updatetime", "#{updatetime,jdbcType=VARCHAR}");
        }

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public String selectByExample(FundCalendarExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("taid,fundcode,idate");
        } else {
            SELECT("taid,fundcode,idate");
        }
        SELECT("marketflag");
        SELECT("updatetime");

        FROM("FUND_CALENDAR");
        applyWhere(example, false);

        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        FundCalendar record = (FundCalendar) parameter.get("record");
        FundCalendarExample example = (FundCalendarExample) parameter.get("example");

        BEGIN();
        UPDATE("FUND_CALENDAR");

        if (record.getTaid() != null) {
            SET("taid = #{record.taid,jdbcType=VARCHAR}");
        }
        if (record.getFundcode() != null) {
            SET("fundcode = #{record.fundcode,jdbcType=VARCHAR}");
        }
        if (record.getIdate() != null) {
            SET("idate = #{record.idate,jdbcType=VARCHAR}");
        }
        if (record.getMarketflag() != null) {
            SET("marketflag = #{record.marketflag,jdbcType=VARCHAR}");
        }
        if (record.getUpdatetime() != null) {
            SET("updatetime = #{record.updatetime,jdbcType=VARCHAR}");
        }

        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("FUND_CALENDAR");

        SET("taid = #{record.taid,jdbcType=VARCHAR}");
        SET("fundcode = #{record.fundcode,jdbcType=VARCHAR}");
        SET("idate = #{record.idate,jdbcType=VARCHAR}");
        SET("marketflag = #{record.marketflag,jdbcType=VARCHAR}");
        SET("updatetime = #{record.updatetime,jdbcType=VARCHAR}");

        FundCalendarExample example = (FundCalendarExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(FundCalendar record) {
        BEGIN();
        UPDATE("FUND_CALENDAR");

        if (record.getMarketflag() != null) {
            SET("userEmail = #{marketflag,jdbcType=VARCHAR}");
        }
        if (record.getUpdatetime() != null) {
            SET("userEmail = #{updatetime,jdbcType=VARCHAR}");
        }

        WHERE("1=1"
            + " and taid = #{taid,jdbcType=VARCHAR}"
            + " and fundcode = #{fundcode,jdbcType=VARCHAR}"
            + " and idate = #{idate,jdbcType=VARCHAR}"
            );

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    protected void applyWhere(FundCalendarExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value<#noparse>} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s<#noparse>} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}