package test;

public class kfatKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TRANS.DISTRIBUTORCODE
     *
     * @mbggenerated
     */
    private String distributorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_TRANS.APPSHEETSERIALNO
     *
     * @mbggenerated
     */
    private String appsheetserialno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TRANS.DISTRIBUTORCODE
     *
     * @return the value of APP_TRANS.DISTRIBUTORCODE
     *
     * @mbggenerated
     */
    public String getDistributorcode() {
        return distributorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TRANS.DISTRIBUTORCODE
     *
     * @param distributorcode the value for APP_TRANS.DISTRIBUTORCODE
     *
     * @mbggenerated
     */
    public void setDistributorcode(String distributorcode) {
        this.distributorcode = distributorcode == null ? null : distributorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_TRANS.APPSHEETSERIALNO
     *
     * @return the value of APP_TRANS.APPSHEETSERIALNO
     *
     * @mbggenerated
     */
    public String getAppsheetserialno() {
        return appsheetserialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_TRANS.APPSHEETSERIALNO
     *
     * @param appsheetserialno the value for APP_TRANS.APPSHEETSERIALNO
     *
     * @mbggenerated
     */
    public void setAppsheetserialno(String appsheetserialno) {
        this.appsheetserialno = appsheetserialno == null ? null : appsheetserialno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        kfatKey other = (kfatKey) that;
        return (this.getDistributorcode() == null ? other.getDistributorcode() == null : this.getDistributorcode().equals(other.getDistributorcode()))
            && (this.getAppsheetserialno() == null ? other.getAppsheetserialno() == null : this.getAppsheetserialno().equals(other.getAppsheetserialno()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDistributorcode() == null) ? 0 : getDistributorcode().hashCode());
        result = prime * result + ((getAppsheetserialno() == null) ? 0 : getAppsheetserialno().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        kfatKey other = (kfatKey) that;
        return (this.getDistributorcode() == null ? other.getDistributorcode() == null : this.getDistributorcode().equals(other.getDistributorcode()))
            && (this.getAppsheetserialno() == null ? other.getAppsheetserialno() == null : this.getAppsheetserialno().equals(other.getAppsheetserialno()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDistributorcode() == null) ? 0 : getDistributorcode().hashCode());
        result = prime * result + ((getAppsheetserialno() == null) ? 0 : getAppsheetserialno().hashCode());
        return result;
    }
}