package test;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import test.kfat;
import test.kfatExample.Criteria;
import test.kfatExample.Criterion;
import test.kfatExample;

public class kfatSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    public String countByExample(kfatExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("APP_TRANS");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    public String deleteByExample(kfatExample example) {
        BEGIN();
        DELETE_FROM("APP_TRANS");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    public String insertSelective(kfat record) {
        BEGIN();
        INSERT_INTO("APP_TRANS");
        
        if (record.getDistributorcode() != null) {
            VALUES("DISTRIBUTORCODE", "#{distributorcode,jdbcType=CHAR}");
        }
        
        if (record.getAppsheetserialno() != null) {
            VALUES("APPSHEETSERIALNO", "#{appsheetserialno,jdbcType=VARCHAR}");
        }
        
        if (record.getIodate() != null) {
            VALUES("IODATE", "#{iodate,jdbcType=CHAR}");
        }
        
        if (record.getSno() != null) {
            VALUES("SNO", "#{sno,jdbcType=DECIMAL}");
        }
        
        if (record.getReturnmsg() != null) {
            VALUES("RETURNMSG", "#{returnmsg,jdbcType=VARCHAR}");
        }
        
        if (record.getReturncode() != null) {
            VALUES("RETURNCODE", "#{returncode,jdbcType=CHAR}");
        }
        
        if (record.getTano() != null) {
            VALUES("TANO", "#{tano,jdbcType=CHAR}");
        }
        
        if (record.getTransactioncfmdate() != null) {
            VALUES("TRANSACTIONCFMDATE", "#{transactioncfmdate,jdbcType=CHAR}");
        }
        
        if (record.getTaserialno() != null) {
            VALUES("TASERIALNO", "#{taserialno,jdbcType=VARCHAR}");
        }
        
        if (record.getBusinesscode() != null) {
            VALUES("BUSINESSCODE", "#{businesscode,jdbcType=CHAR}");
        }
        
        if (record.getBusinesscodeApp() != null) {
            VALUES("BUSINESSCODE_APP", "#{businesscodeApp,jdbcType=CHAR}");
        }
        
        if (record.getCustno() != null) {
            VALUES("CUSTNO", "#{custno,jdbcType=DECIMAL}");
        }
        
        if (record.getCusttp() != null) {
            VALUES("CUSTTP", "#{custtp,jdbcType=CHAR}");
        }
        
        if (record.getCustfullname() != null) {
            VALUES("CUSTFULLNAME", "#{custfullname,jdbcType=VARCHAR}");
        }
        
        if (record.getCustgroup() != null) {
            VALUES("CUSTGROUP", "#{custgroup,jdbcType=CHAR}");
        }
        
        if (record.getCustclass1() != null) {
            VALUES("CUSTCLASS1", "#{custclass1,jdbcType=VARCHAR}");
        }
        
        if (record.getCustclass2() != null) {
            VALUES("CUSTCLASS2", "#{custclass2,jdbcType=VARCHAR}");
        }
        
        if (record.getTaaccountid() != null) {
            VALUES("TAACCOUNTID", "#{taaccountid,jdbcType=CHAR}");
        }
        
        if (record.getTaaccountidApp() != null) {
            VALUES("TAACCOUNTID_APP", "#{taaccountidApp,jdbcType=CHAR}");
        }
        
        if (record.getTransactiondate() != null) {
            VALUES("TRANSACTIONDATE", "#{transactiondate,jdbcType=CHAR}");
        }
        
        if (record.getTransactiontime() != null) {
            VALUES("TRANSACTIONTIME", "#{transactiontime,jdbcType=CHAR}");
        }
        
        if (record.getOperdate() != null) {
            VALUES("OPERDATE", "#{operdate,jdbcType=CHAR}");
        }
        
        if (record.getOpertime() != null) {
            VALUES("OPERTIME", "#{opertime,jdbcType=CHAR}");
        }
        
        if (record.getTransactionaccountid() != null) {
            VALUES("TRANSACTIONACCOUNTID", "#{transactionaccountid,jdbcType=VARCHAR}");
        }
        
        if (record.getBranchcode() != null) {
            VALUES("BRANCHCODE", "#{branchcode,jdbcType=VARCHAR}");
        }
        
        if (record.getFundcode() != null) {
            VALUES("FUNDCODE", "#{fundcode,jdbcType=CHAR}");
        }
        
        if (record.getSharetype() != null) {
            VALUES("SHARETYPE", "#{sharetype,jdbcType=CHAR}");
        }
        
        if (record.getCurrencytype() != null) {
            VALUES("CURRENCYTYPE", "#{currencytype,jdbcType=CHAR}");
        }
        
        if (record.getApplicationvol() != null) {
            VALUES("APPLICATIONVOL", "#{applicationvol,jdbcType=DECIMAL}");
        }
        
        if (record.getApplicationamount() != null) {
            VALUES("APPLICATIONAMOUNT", "#{applicationamount,jdbcType=DECIMAL}");
        }
        
        if (record.getOriginapplicationvol() != null) {
            VALUES("ORIGINAPPLICATIONVOL", "#{originapplicationvol,jdbcType=DECIMAL}");
        }
        
        if (record.getOriginapplicationamount() != null) {
            VALUES("ORIGINAPPLICATIONAMOUNT", "#{originapplicationamount,jdbcType=DECIMAL}");
        }
        
        if (record.getDiscountrate() != null) {
            VALUES("DISCOUNTRATE", "#{discountrate,jdbcType=DECIMAL}");
        }
        
        if (record.getOrigindiscountrate() != null) {
            VALUES("ORIGINDISCOUNTRATE", "#{origindiscountrate,jdbcType=DECIMAL}");
        }
        
        if (record.getTargettaaccountid() != null) {
            VALUES("TARGETTAACCOUNTID", "#{targettaaccountid,jdbcType=CHAR}");
        }
        
        if (record.getTargetdistributorcode() != null) {
            VALUES("TARGETDISTRIBUTORCODE", "#{targetdistributorcode,jdbcType=CHAR}");
        }
        
        if (record.getTargettransactionaccountid() != null) {
            VALUES("TARGETTRANSACTIONACCOUNTID", "#{targettransactionaccountid,jdbcType=VARCHAR}");
        }
        
        if (record.getTargetbranchcode() != null) {
            VALUES("TARGETBRANCHCODE", "#{targetbranchcode,jdbcType=VARCHAR}");
        }
        
        if (record.getTargetregioncode() != null) {
            VALUES("TARGETREGIONCODE", "#{targetregioncode,jdbcType=CHAR}");
        }
        
        if (record.getTargetfundcode() != null) {
            VALUES("TARGETFUNDCODE", "#{targetfundcode,jdbcType=CHAR}");
        }
        
        if (record.getTargetsharetype() != null) {
            VALUES("TARGETSHARETYPE", "#{targetsharetype,jdbcType=CHAR}");
        }
        
        if (record.getUploaddate() != null) {
            VALUES("UPLOADDATE", "#{uploaddate,jdbcType=CHAR}");
        }
        
        if (record.getOriginalserialno() != null) {
            VALUES("ORIGINALSERIALNO", "#{originalserialno,jdbcType=VARCHAR}");
        }
        
        if (record.getOriginalcfmdate() != null) {
            VALUES("ORIGINALCFMDATE", "#{originalcfmdate,jdbcType=CHAR}");
        }
        
        if (record.getOriginalappsheetno() != null) {
            VALUES("ORIGINALAPPSHEETNO", "#{originalappsheetno,jdbcType=VARCHAR}");
        }
        
        if (record.getOriginalappdate() != null) {
            VALUES("ORIGINALAPPDATE", "#{originalappdate,jdbcType=CHAR}");
        }
        
        if (record.getOriginalsubsdate() != null) {
            VALUES("ORIGINALSUBSDATE", "#{originalsubsdate,jdbcType=CHAR}");
        }
        
        if (record.getInvtp() != null) {
            VALUES("INVTP", "#{invtp,jdbcType=CHAR}");
        }
        
        if (record.getRegioncode() != null) {
            VALUES("REGIONCODE", "#{regioncode,jdbcType=CHAR}");
        }
        
        if (record.getDepositacct() != null) {
            VALUES("DEPOSITACCT", "#{depositacct,jdbcType=VARCHAR}");
        }
        
        if (record.getShareclass() != null) {
            VALUES("SHARECLASS", "#{shareclass,jdbcType=CHAR}");
        }
        
        if (record.getValidperiod() != null) {
            VALUES("VALIDPERIOD", "#{validperiod,jdbcType=DECIMAL}");
        }
        
        if (record.getDefdividendmethod() != null) {
            VALUES("DEFDIVIDENDMETHOD", "#{defdividendmethod,jdbcType=CHAR}");
        }
        
        if (record.getDividendratio() != null) {
            VALUES("DIVIDENDRATIO", "#{dividendratio,jdbcType=DECIMAL}");
        }
        
        if (record.getFuturebuydate() != null) {
            VALUES("FUTUREBUYDATE", "#{futurebuydate,jdbcType=CHAR}");
        }
        
        if (record.getContractno() != null) {
            VALUES("CONTRACTNO", "#{contractno,jdbcType=VARCHAR}");
        }
        
        if (record.getProtocolno() != null) {
            VALUES("PROTOCOLNO", "#{protocolno,jdbcType=VARCHAR}");
        }
        
        if (record.getBegindateofperiodicsubs() != null) {
            VALUES("BEGINDATEOFPERIODICSUBS", "#{begindateofperiodicsubs,jdbcType=CHAR}");
        }
        
        if (record.getEnddateofperiodicsubs() != null) {
            VALUES("ENDDATEOFPERIODICSUBS", "#{enddateofperiodicsubs,jdbcType=CHAR}");
        }
        
        if (record.getProtocalenddate() != null) {
            VALUES("PROTOCALENDDATE", "#{protocalenddate,jdbcType=CHAR}");
        }
        
        if (record.getDateofperiodicsubs() != null) {
            VALUES("DATEOFPERIODICSUBS", "#{dateofperiodicsubs,jdbcType=CHAR}");
        }
        
        if (record.getRationterm() != null) {
            VALUES("RATIONTERM", "#{rationterm,jdbcType=VARCHAR}");
        }
        
        if (record.getRationdate() != null) {
            VALUES("RATIONDATE", "#{rationdate,jdbcType=DECIMAL}");
        }
        
        if (record.getSaveplanflag() != null) {
            VALUES("SAVEPLANFLAG", "#{saveplanflag,jdbcType=CHAR}");
        }
        
        if (record.getRegisterdate() != null) {
            VALUES("REGISTERDATE", "#{registerdate,jdbcType=CHAR}");
        }
        
        if (record.getSpecifyredeemflag() != null) {
            VALUES("SPECIFYREDEEMFLAG", "#{specifyredeemflag,jdbcType=CHAR}");
        }
        
        if (record.getRedemptioninadvanceflag() != null) {
            VALUES("REDEMPTIONINADVANCEFLAG", "#{redemptioninadvanceflag,jdbcType=CHAR}");
        }
        
        if (record.getRedemptiondateinadvance() != null) {
            VALUES("REDEMPTIONDATEINADVANCE", "#{redemptiondateinadvance,jdbcType=CHAR}");
        }
        
        if (record.getDaysredemptioninadvance() != null) {
            VALUES("DAYSREDEMPTIONINADVANCE", "#{daysredemptioninadvance,jdbcType=DECIMAL}");
        }
        
        if (record.getRedemptionreason() != null) {
            VALUES("REDEMPTIONREASON", "#{redemptionreason,jdbcType=CHAR}");
        }
        
        if (record.getLargeredemptionflag() != null) {
            VALUES("LARGEREDEMPTIONFLAG", "#{largeredemptionflag,jdbcType=CHAR}");
        }
        
        if (record.getFrozencause() != null) {
            VALUES("FROZENCAUSE", "#{frozencause,jdbcType=CHAR}");
        }
        
        if (record.getFreezingdeadline() != null) {
            VALUES("FREEZINGDEADLINE", "#{freezingdeadline,jdbcType=CHAR}");
        }
        
        if (record.getCharge() != null) {
            VALUES("CHARGE", "#{charge,jdbcType=DECIMAL}");
        }
        
        if (record.getHavematchqty() != null) {
            VALUES("HAVEMATCHQTY", "#{havematchqty,jdbcType=DECIMAL}");
        }
        
        if (record.getTotalbackendload() != null) {
            VALUES("TOTALBACKENDLOAD", "#{totalbackendload,jdbcType=DECIMAL}");
        }
        
        if (record.getDetailflag() != null) {
            VALUES("DETAILFLAG", "#{detailflag,jdbcType=CHAR}");
        }
        
        if (record.getSpecification() != null) {
            VALUES("SPECIFICATION", "#{specification,jdbcType=VARCHAR}");
        }
        
        if (record.getFromtaflag() != null) {
            VALUES("FROMTAFLAG", "#{fromtaflag,jdbcType=CHAR}");
        }
        
        if (record.getMoneyaccount() != null) {
            VALUES("MONEYACCOUNT", "#{moneyaccount,jdbcType=DECIMAL}");
        }
        
        if (record.getCenterno() != null) {
            VALUES("CENTERNO", "#{centerno,jdbcType=VARCHAR}");
        }
        
        if (record.getNetno() != null) {
            VALUES("NETNO", "#{netno,jdbcType=VARCHAR}");
        }
        
        if (record.getChannelid() != null) {
            VALUES("CHANNELID", "#{channelid,jdbcType=VARCHAR}");
        }
        
        if (record.getPaycenterid() != null) {
            VALUES("PAYCENTERID", "#{paycenterid,jdbcType=VARCHAR}");
        }
        
        if (record.getCustmanagerid() != null) {
            VALUES("CUSTMANAGERID", "#{custmanagerid,jdbcType=VARCHAR}");
        }
        
        if (record.getFinancingmanagerid() != null) {
            VALUES("FINANCINGMANAGERID", "#{financingmanagerid,jdbcType=VARCHAR}");
        }
        
        if (record.getReferral() != null) {
            VALUES("REFERRAL", "#{referral,jdbcType=VARCHAR}");
        }
        
        if (record.getReferralprov() != null) {
            VALUES("REFERRALPROV", "#{referralprov,jdbcType=VARCHAR}");
        }
        
        if (record.getReferralcity() != null) {
            VALUES("REFERRALCITY", "#{referralcity,jdbcType=VARCHAR}");
        }
        
        if (record.getReferralmobile() != null) {
            VALUES("REFERRALMOBILE", "#{referralmobile,jdbcType=VARCHAR}");
        }
        
        if (record.getSalespromotion() != null) {
            VALUES("SALESPROMOTION", "#{salespromotion,jdbcType=VARCHAR}");
        }
        
        if (record.getOperid() != null) {
            VALUES("OPERID", "#{operid,jdbcType=VARCHAR}");
        }
        
        if (record.getNetaddr() != null) {
            VALUES("NETADDR", "#{netaddr,jdbcType=VARCHAR}");
        }
        
        if (record.getCancelflag() != null) {
            VALUES("CANCELFLAG", "#{cancelflag,jdbcType=CHAR}");
        }
        
        if (record.getPrestatus() != null) {
            VALUES("PRESTATUS", "#{prestatus,jdbcType=CHAR}");
        }
        
        if (record.getPaystatus() != null) {
            VALUES("PAYSTATUS", "#{paystatus,jdbcType=CHAR}");
        }
        
        if (record.getStatus() != null) {
            VALUES("STATUS", "#{status,jdbcType=CHAR}");
        }
        
        if (record.getLastStatus() != null) {
            VALUES("LAST_STATUS", "#{lastStatus,jdbcType=CHAR}");
        }
        
        if (record.getRiskmatching() != null) {
            VALUES("RISKMATCHING", "#{riskmatching,jdbcType=CHAR}");
        }
        
        if (record.getOrderflag() != null) {
            VALUES("ORDERFLAG", "#{orderflag,jdbcType=CHAR}");
        }
        
        if (record.getExceptionalflag() != null) {
            VALUES("EXCEPTIONALFLAG", "#{exceptionalflag,jdbcType=CHAR}");
        }
        
        if (record.getOperway() != null) {
            VALUES("OPERWAY", "#{operway,jdbcType=CHAR}");
        }
        
        if (record.getOperorg() != null) {
            VALUES("OPERORG", "#{operorg,jdbcType=VARCHAR}");
        }
        
        if (record.getBusinesskind() != null) {
            VALUES("BUSINESSKIND", "#{businesskind,jdbcType=CHAR}");
        }
        
        if (record.getTransactorcerttype() != null) {
            VALUES("TRANSACTORCERTTYPE", "#{transactorcerttype,jdbcType=CHAR}");
        }
        
        if (record.getTransactorcertno() != null) {
            VALUES("TRANSACTORCERTNO", "#{transactorcertno,jdbcType=VARCHAR}");
        }
        
        if (record.getTransactorname() != null) {
            VALUES("TRANSACTORNAME", "#{transactorname,jdbcType=VARCHAR}");
        }
        
        if (record.getAcceptmethod() != null) {
            VALUES("ACCEPTMETHOD", "#{acceptmethod,jdbcType=CHAR}");
        }
        
        if (record.getTransactoridstr() != null) {
            VALUES("TRANSACTORIDSTR", "#{transactoridstr,jdbcType=VARCHAR}");
        }
        
        if (record.getTransactornamestr() != null) {
            VALUES("TRANSACTORNAMESTR", "#{transactornamestr,jdbcType=VARCHAR}");
        }
        
        if (record.getPaytype() != null) {
            VALUES("PAYTYPE", "#{paytype,jdbcType=CHAR}");
        }
        
        if (record.getOrginchannelid() != null) {
            VALUES("ORGINCHANNELID", "#{orginchannelid,jdbcType=VARCHAR}");
        }
        
        if (record.getSource() != null) {
            VALUES("SOURCE", "#{source,jdbcType=CHAR}");
        }
        
        if (record.getSeatcode() != null) {
            VALUES("SEATCODE", "#{seatcode,jdbcType=VARCHAR}");
        }
        
        if (record.getSecuritiesaccountid() != null) {
            VALUES("SECURITIESACCOUNTID", "#{securitiesaccountid,jdbcType=VARCHAR}");
        }
        
        if (record.getRejectmsg() != null) {
            VALUES("REJECTMSG", "#{rejectmsg,jdbcType=VARCHAR}");
        }
        
        if (record.getIsreedom() != null) {
            VALUES("ISREEDOM", "#{isreedom,jdbcType=CHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    public String selectByExample(kfatExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("DISTRIBUTORCODE");
        } else {
            SELECT("DISTRIBUTORCODE");
        }
        SELECT("APPSHEETSERIALNO");
        SELECT("IODATE");
        SELECT("SNO");
        SELECT("RETURNMSG");
        SELECT("RETURNCODE");
        SELECT("TANO");
        SELECT("TRANSACTIONCFMDATE");
        SELECT("TASERIALNO");
        SELECT("BUSINESSCODE");
        SELECT("BUSINESSCODE_APP");
        SELECT("CUSTNO");
        SELECT("CUSTTP");
        SELECT("CUSTFULLNAME");
        SELECT("CUSTGROUP");
        SELECT("CUSTCLASS1");
        SELECT("CUSTCLASS2");
        SELECT("TAACCOUNTID");
        SELECT("TAACCOUNTID_APP");
        SELECT("TRANSACTIONDATE");
        SELECT("TRANSACTIONTIME");
        SELECT("OPERDATE");
        SELECT("OPERTIME");
        SELECT("TRANSACTIONACCOUNTID");
        SELECT("BRANCHCODE");
        SELECT("FUNDCODE");
        SELECT("SHARETYPE");
        SELECT("CURRENCYTYPE");
        SELECT("APPLICATIONVOL");
        SELECT("APPLICATIONAMOUNT");
        SELECT("ORIGINAPPLICATIONVOL");
        SELECT("ORIGINAPPLICATIONAMOUNT");
        SELECT("DISCOUNTRATE");
        SELECT("ORIGINDISCOUNTRATE");
        SELECT("TARGETTAACCOUNTID");
        SELECT("TARGETDISTRIBUTORCODE");
        SELECT("TARGETTRANSACTIONACCOUNTID");
        SELECT("TARGETBRANCHCODE");
        SELECT("TARGETREGIONCODE");
        SELECT("TARGETFUNDCODE");
        SELECT("TARGETSHARETYPE");
        SELECT("UPLOADDATE");
        SELECT("ORIGINALSERIALNO");
        SELECT("ORIGINALCFMDATE");
        SELECT("ORIGINALAPPSHEETNO");
        SELECT("ORIGINALAPPDATE");
        SELECT("ORIGINALSUBSDATE");
        SELECT("INVTP");
        SELECT("REGIONCODE");
        SELECT("DEPOSITACCT");
        SELECT("SHARECLASS");
        SELECT("VALIDPERIOD");
        SELECT("DEFDIVIDENDMETHOD");
        SELECT("DIVIDENDRATIO");
        SELECT("FUTUREBUYDATE");
        SELECT("CONTRACTNO");
        SELECT("PROTOCOLNO");
        SELECT("BEGINDATEOFPERIODICSUBS");
        SELECT("ENDDATEOFPERIODICSUBS");
        SELECT("PROTOCALENDDATE");
        SELECT("DATEOFPERIODICSUBS");
        SELECT("RATIONTERM");
        SELECT("RATIONDATE");
        SELECT("SAVEPLANFLAG");
        SELECT("REGISTERDATE");
        SELECT("SPECIFYREDEEMFLAG");
        SELECT("REDEMPTIONINADVANCEFLAG");
        SELECT("REDEMPTIONDATEINADVANCE");
        SELECT("DAYSREDEMPTIONINADVANCE");
        SELECT("REDEMPTIONREASON");
        SELECT("LARGEREDEMPTIONFLAG");
        SELECT("FROZENCAUSE");
        SELECT("FREEZINGDEADLINE");
        SELECT("CHARGE");
        SELECT("HAVEMATCHQTY");
        SELECT("TOTALBACKENDLOAD");
        SELECT("DETAILFLAG");
        SELECT("SPECIFICATION");
        SELECT("FROMTAFLAG");
        SELECT("MONEYACCOUNT");
        SELECT("CENTERNO");
        SELECT("NETNO");
        SELECT("CHANNELID");
        SELECT("PAYCENTERID");
        SELECT("CUSTMANAGERID");
        SELECT("FINANCINGMANAGERID");
        SELECT("REFERRAL");
        SELECT("REFERRALPROV");
        SELECT("REFERRALCITY");
        SELECT("REFERRALMOBILE");
        SELECT("SALESPROMOTION");
        SELECT("OPERID");
        SELECT("NETADDR");
        SELECT("CANCELFLAG");
        SELECT("PRESTATUS");
        SELECT("PAYSTATUS");
        SELECT("STATUS");
        SELECT("LAST_STATUS");
        SELECT("RISKMATCHING");
        SELECT("ORDERFLAG");
        SELECT("EXCEPTIONALFLAG");
        SELECT("OPERWAY");
        SELECT("OPERORG");
        SELECT("BUSINESSKIND");
        SELECT("TRANSACTORCERTTYPE");
        SELECT("TRANSACTORCERTNO");
        SELECT("TRANSACTORNAME");
        SELECT("ACCEPTMETHOD");
        SELECT("TRANSACTORIDSTR");
        SELECT("TRANSACTORNAMESTR");
        SELECT("PAYTYPE");
        SELECT("ORGINCHANNELID");
        SELECT("SOURCE");
        SELECT("SEATCODE");
        SELECT("SECURITIESACCOUNTID");
        SELECT("REJECTMSG");
        SELECT("ISREEDOM");
        FROM("APP_TRANS");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        kfat record = (kfat) parameter.get("record");
        kfatExample example = (kfatExample) parameter.get("example");
        
        BEGIN();
        UPDATE("APP_TRANS");
        
        if (record.getDistributorcode() != null) {
            SET("DISTRIBUTORCODE = #{record.distributorcode,jdbcType=CHAR}");
        }
        
        if (record.getAppsheetserialno() != null) {
            SET("APPSHEETSERIALNO = #{record.appsheetserialno,jdbcType=VARCHAR}");
        }
        
        if (record.getIodate() != null) {
            SET("IODATE = #{record.iodate,jdbcType=CHAR}");
        }
        
        if (record.getSno() != null) {
            SET("SNO = #{record.sno,jdbcType=DECIMAL}");
        }
        
        if (record.getReturnmsg() != null) {
            SET("RETURNMSG = #{record.returnmsg,jdbcType=VARCHAR}");
        }
        
        if (record.getReturncode() != null) {
            SET("RETURNCODE = #{record.returncode,jdbcType=CHAR}");
        }
        
        if (record.getTano() != null) {
            SET("TANO = #{record.tano,jdbcType=CHAR}");
        }
        
        if (record.getTransactioncfmdate() != null) {
            SET("TRANSACTIONCFMDATE = #{record.transactioncfmdate,jdbcType=CHAR}");
        }
        
        if (record.getTaserialno() != null) {
            SET("TASERIALNO = #{record.taserialno,jdbcType=VARCHAR}");
        }
        
        if (record.getBusinesscode() != null) {
            SET("BUSINESSCODE = #{record.businesscode,jdbcType=CHAR}");
        }
        
        if (record.getBusinesscodeApp() != null) {
            SET("BUSINESSCODE_APP = #{record.businesscodeApp,jdbcType=CHAR}");
        }
        
        if (record.getCustno() != null) {
            SET("CUSTNO = #{record.custno,jdbcType=DECIMAL}");
        }
        
        if (record.getCusttp() != null) {
            SET("CUSTTP = #{record.custtp,jdbcType=CHAR}");
        }
        
        if (record.getCustfullname() != null) {
            SET("CUSTFULLNAME = #{record.custfullname,jdbcType=VARCHAR}");
        }
        
        if (record.getCustgroup() != null) {
            SET("CUSTGROUP = #{record.custgroup,jdbcType=CHAR}");
        }
        
        if (record.getCustclass1() != null) {
            SET("CUSTCLASS1 = #{record.custclass1,jdbcType=VARCHAR}");
        }
        
        if (record.getCustclass2() != null) {
            SET("CUSTCLASS2 = #{record.custclass2,jdbcType=VARCHAR}");
        }
        
        if (record.getTaaccountid() != null) {
            SET("TAACCOUNTID = #{record.taaccountid,jdbcType=CHAR}");
        }
        
        if (record.getTaaccountidApp() != null) {
            SET("TAACCOUNTID_APP = #{record.taaccountidApp,jdbcType=CHAR}");
        }
        
        if (record.getTransactiondate() != null) {
            SET("TRANSACTIONDATE = #{record.transactiondate,jdbcType=CHAR}");
        }
        
        if (record.getTransactiontime() != null) {
            SET("TRANSACTIONTIME = #{record.transactiontime,jdbcType=CHAR}");
        }
        
        if (record.getOperdate() != null) {
            SET("OPERDATE = #{record.operdate,jdbcType=CHAR}");
        }
        
        if (record.getOpertime() != null) {
            SET("OPERTIME = #{record.opertime,jdbcType=CHAR}");
        }
        
        if (record.getTransactionaccountid() != null) {
            SET("TRANSACTIONACCOUNTID = #{record.transactionaccountid,jdbcType=VARCHAR}");
        }
        
        if (record.getBranchcode() != null) {
            SET("BRANCHCODE = #{record.branchcode,jdbcType=VARCHAR}");
        }
        
        if (record.getFundcode() != null) {
            SET("FUNDCODE = #{record.fundcode,jdbcType=CHAR}");
        }
        
        if (record.getSharetype() != null) {
            SET("SHARETYPE = #{record.sharetype,jdbcType=CHAR}");
        }
        
        if (record.getCurrencytype() != null) {
            SET("CURRENCYTYPE = #{record.currencytype,jdbcType=CHAR}");
        }
        
        if (record.getApplicationvol() != null) {
            SET("APPLICATIONVOL = #{record.applicationvol,jdbcType=DECIMAL}");
        }
        
        if (record.getApplicationamount() != null) {
            SET("APPLICATIONAMOUNT = #{record.applicationamount,jdbcType=DECIMAL}");
        }
        
        if (record.getOriginapplicationvol() != null) {
            SET("ORIGINAPPLICATIONVOL = #{record.originapplicationvol,jdbcType=DECIMAL}");
        }
        
        if (record.getOriginapplicationamount() != null) {
            SET("ORIGINAPPLICATIONAMOUNT = #{record.originapplicationamount,jdbcType=DECIMAL}");
        }
        
        if (record.getDiscountrate() != null) {
            SET("DISCOUNTRATE = #{record.discountrate,jdbcType=DECIMAL}");
        }
        
        if (record.getOrigindiscountrate() != null) {
            SET("ORIGINDISCOUNTRATE = #{record.origindiscountrate,jdbcType=DECIMAL}");
        }
        
        if (record.getTargettaaccountid() != null) {
            SET("TARGETTAACCOUNTID = #{record.targettaaccountid,jdbcType=CHAR}");
        }
        
        if (record.getTargetdistributorcode() != null) {
            SET("TARGETDISTRIBUTORCODE = #{record.targetdistributorcode,jdbcType=CHAR}");
        }
        
        if (record.getTargettransactionaccountid() != null) {
            SET("TARGETTRANSACTIONACCOUNTID = #{record.targettransactionaccountid,jdbcType=VARCHAR}");
        }
        
        if (record.getTargetbranchcode() != null) {
            SET("TARGETBRANCHCODE = #{record.targetbranchcode,jdbcType=VARCHAR}");
        }
        
        if (record.getTargetregioncode() != null) {
            SET("TARGETREGIONCODE = #{record.targetregioncode,jdbcType=CHAR}");
        }
        
        if (record.getTargetfundcode() != null) {
            SET("TARGETFUNDCODE = #{record.targetfundcode,jdbcType=CHAR}");
        }
        
        if (record.getTargetsharetype() != null) {
            SET("TARGETSHARETYPE = #{record.targetsharetype,jdbcType=CHAR}");
        }
        
        if (record.getUploaddate() != null) {
            SET("UPLOADDATE = #{record.uploaddate,jdbcType=CHAR}");
        }
        
        if (record.getOriginalserialno() != null) {
            SET("ORIGINALSERIALNO = #{record.originalserialno,jdbcType=VARCHAR}");
        }
        
        if (record.getOriginalcfmdate() != null) {
            SET("ORIGINALCFMDATE = #{record.originalcfmdate,jdbcType=CHAR}");
        }
        
        if (record.getOriginalappsheetno() != null) {
            SET("ORIGINALAPPSHEETNO = #{record.originalappsheetno,jdbcType=VARCHAR}");
        }
        
        if (record.getOriginalappdate() != null) {
            SET("ORIGINALAPPDATE = #{record.originalappdate,jdbcType=CHAR}");
        }
        
        if (record.getOriginalsubsdate() != null) {
            SET("ORIGINALSUBSDATE = #{record.originalsubsdate,jdbcType=CHAR}");
        }
        
        if (record.getInvtp() != null) {
            SET("INVTP = #{record.invtp,jdbcType=CHAR}");
        }
        
        if (record.getRegioncode() != null) {
            SET("REGIONCODE = #{record.regioncode,jdbcType=CHAR}");
        }
        
        if (record.getDepositacct() != null) {
            SET("DEPOSITACCT = #{record.depositacct,jdbcType=VARCHAR}");
        }
        
        if (record.getShareclass() != null) {
            SET("SHARECLASS = #{record.shareclass,jdbcType=CHAR}");
        }
        
        if (record.getValidperiod() != null) {
            SET("VALIDPERIOD = #{record.validperiod,jdbcType=DECIMAL}");
        }
        
        if (record.getDefdividendmethod() != null) {
            SET("DEFDIVIDENDMETHOD = #{record.defdividendmethod,jdbcType=CHAR}");
        }
        
        if (record.getDividendratio() != null) {
            SET("DIVIDENDRATIO = #{record.dividendratio,jdbcType=DECIMAL}");
        }
        
        if (record.getFuturebuydate() != null) {
            SET("FUTUREBUYDATE = #{record.futurebuydate,jdbcType=CHAR}");
        }
        
        if (record.getContractno() != null) {
            SET("CONTRACTNO = #{record.contractno,jdbcType=VARCHAR}");
        }
        
        if (record.getProtocolno() != null) {
            SET("PROTOCOLNO = #{record.protocolno,jdbcType=VARCHAR}");
        }
        
        if (record.getBegindateofperiodicsubs() != null) {
            SET("BEGINDATEOFPERIODICSUBS = #{record.begindateofperiodicsubs,jdbcType=CHAR}");
        }
        
        if (record.getEnddateofperiodicsubs() != null) {
            SET("ENDDATEOFPERIODICSUBS = #{record.enddateofperiodicsubs,jdbcType=CHAR}");
        }
        
        if (record.getProtocalenddate() != null) {
            SET("PROTOCALENDDATE = #{record.protocalenddate,jdbcType=CHAR}");
        }
        
        if (record.getDateofperiodicsubs() != null) {
            SET("DATEOFPERIODICSUBS = #{record.dateofperiodicsubs,jdbcType=CHAR}");
        }
        
        if (record.getRationterm() != null) {
            SET("RATIONTERM = #{record.rationterm,jdbcType=VARCHAR}");
        }
        
        if (record.getRationdate() != null) {
            SET("RATIONDATE = #{record.rationdate,jdbcType=DECIMAL}");
        }
        
        if (record.getSaveplanflag() != null) {
            SET("SAVEPLANFLAG = #{record.saveplanflag,jdbcType=CHAR}");
        }
        
        if (record.getRegisterdate() != null) {
            SET("REGISTERDATE = #{record.registerdate,jdbcType=CHAR}");
        }
        
        if (record.getSpecifyredeemflag() != null) {
            SET("SPECIFYREDEEMFLAG = #{record.specifyredeemflag,jdbcType=CHAR}");
        }
        
        if (record.getRedemptioninadvanceflag() != null) {
            SET("REDEMPTIONINADVANCEFLAG = #{record.redemptioninadvanceflag,jdbcType=CHAR}");
        }
        
        if (record.getRedemptiondateinadvance() != null) {
            SET("REDEMPTIONDATEINADVANCE = #{record.redemptiondateinadvance,jdbcType=CHAR}");
        }
        
        if (record.getDaysredemptioninadvance() != null) {
            SET("DAYSREDEMPTIONINADVANCE = #{record.daysredemptioninadvance,jdbcType=DECIMAL}");
        }
        
        if (record.getRedemptionreason() != null) {
            SET("REDEMPTIONREASON = #{record.redemptionreason,jdbcType=CHAR}");
        }
        
        if (record.getLargeredemptionflag() != null) {
            SET("LARGEREDEMPTIONFLAG = #{record.largeredemptionflag,jdbcType=CHAR}");
        }
        
        if (record.getFrozencause() != null) {
            SET("FROZENCAUSE = #{record.frozencause,jdbcType=CHAR}");
        }
        
        if (record.getFreezingdeadline() != null) {
            SET("FREEZINGDEADLINE = #{record.freezingdeadline,jdbcType=CHAR}");
        }
        
        if (record.getCharge() != null) {
            SET("CHARGE = #{record.charge,jdbcType=DECIMAL}");
        }
        
        if (record.getHavematchqty() != null) {
            SET("HAVEMATCHQTY = #{record.havematchqty,jdbcType=DECIMAL}");
        }
        
        if (record.getTotalbackendload() != null) {
            SET("TOTALBACKENDLOAD = #{record.totalbackendload,jdbcType=DECIMAL}");
        }
        
        if (record.getDetailflag() != null) {
            SET("DETAILFLAG = #{record.detailflag,jdbcType=CHAR}");
        }
        
        if (record.getSpecification() != null) {
            SET("SPECIFICATION = #{record.specification,jdbcType=VARCHAR}");
        }
        
        if (record.getFromtaflag() != null) {
            SET("FROMTAFLAG = #{record.fromtaflag,jdbcType=CHAR}");
        }
        
        if (record.getMoneyaccount() != null) {
            SET("MONEYACCOUNT = #{record.moneyaccount,jdbcType=DECIMAL}");
        }
        
        if (record.getCenterno() != null) {
            SET("CENTERNO = #{record.centerno,jdbcType=VARCHAR}");
        }
        
        if (record.getNetno() != null) {
            SET("NETNO = #{record.netno,jdbcType=VARCHAR}");
        }
        
        if (record.getChannelid() != null) {
            SET("CHANNELID = #{record.channelid,jdbcType=VARCHAR}");
        }
        
        if (record.getPaycenterid() != null) {
            SET("PAYCENTERID = #{record.paycenterid,jdbcType=VARCHAR}");
        }
        
        if (record.getCustmanagerid() != null) {
            SET("CUSTMANAGERID = #{record.custmanagerid,jdbcType=VARCHAR}");
        }
        
        if (record.getFinancingmanagerid() != null) {
            SET("FINANCINGMANAGERID = #{record.financingmanagerid,jdbcType=VARCHAR}");
        }
        
        if (record.getReferral() != null) {
            SET("REFERRAL = #{record.referral,jdbcType=VARCHAR}");
        }
        
        if (record.getReferralprov() != null) {
            SET("REFERRALPROV = #{record.referralprov,jdbcType=VARCHAR}");
        }
        
        if (record.getReferralcity() != null) {
            SET("REFERRALCITY = #{record.referralcity,jdbcType=VARCHAR}");
        }
        
        if (record.getReferralmobile() != null) {
            SET("REFERRALMOBILE = #{record.referralmobile,jdbcType=VARCHAR}");
        }
        
        if (record.getSalespromotion() != null) {
            SET("SALESPROMOTION = #{record.salespromotion,jdbcType=VARCHAR}");
        }
        
        if (record.getOperid() != null) {
            SET("OPERID = #{record.operid,jdbcType=VARCHAR}");
        }
        
        if (record.getNetaddr() != null) {
            SET("NETADDR = #{record.netaddr,jdbcType=VARCHAR}");
        }
        
        if (record.getCancelflag() != null) {
            SET("CANCELFLAG = #{record.cancelflag,jdbcType=CHAR}");
        }
        
        if (record.getPrestatus() != null) {
            SET("PRESTATUS = #{record.prestatus,jdbcType=CHAR}");
        }
        
        if (record.getPaystatus() != null) {
            SET("PAYSTATUS = #{record.paystatus,jdbcType=CHAR}");
        }
        
        if (record.getStatus() != null) {
            SET("STATUS = #{record.status,jdbcType=CHAR}");
        }
        
        if (record.getLastStatus() != null) {
            SET("LAST_STATUS = #{record.lastStatus,jdbcType=CHAR}");
        }
        
        if (record.getRiskmatching() != null) {
            SET("RISKMATCHING = #{record.riskmatching,jdbcType=CHAR}");
        }
        
        if (record.getOrderflag() != null) {
            SET("ORDERFLAG = #{record.orderflag,jdbcType=CHAR}");
        }
        
        if (record.getExceptionalflag() != null) {
            SET("EXCEPTIONALFLAG = #{record.exceptionalflag,jdbcType=CHAR}");
        }
        
        if (record.getOperway() != null) {
            SET("OPERWAY = #{record.operway,jdbcType=CHAR}");
        }
        
        if (record.getOperorg() != null) {
            SET("OPERORG = #{record.operorg,jdbcType=VARCHAR}");
        }
        
        if (record.getBusinesskind() != null) {
            SET("BUSINESSKIND = #{record.businesskind,jdbcType=CHAR}");
        }
        
        if (record.getTransactorcerttype() != null) {
            SET("TRANSACTORCERTTYPE = #{record.transactorcerttype,jdbcType=CHAR}");
        }
        
        if (record.getTransactorcertno() != null) {
            SET("TRANSACTORCERTNO = #{record.transactorcertno,jdbcType=VARCHAR}");
        }
        
        if (record.getTransactorname() != null) {
            SET("TRANSACTORNAME = #{record.transactorname,jdbcType=VARCHAR}");
        }
        
        if (record.getAcceptmethod() != null) {
            SET("ACCEPTMETHOD = #{record.acceptmethod,jdbcType=CHAR}");
        }
        
        if (record.getTransactoridstr() != null) {
            SET("TRANSACTORIDSTR = #{record.transactoridstr,jdbcType=VARCHAR}");
        }
        
        if (record.getTransactornamestr() != null) {
            SET("TRANSACTORNAMESTR = #{record.transactornamestr,jdbcType=VARCHAR}");
        }
        
        if (record.getPaytype() != null) {
            SET("PAYTYPE = #{record.paytype,jdbcType=CHAR}");
        }
        
        if (record.getOrginchannelid() != null) {
            SET("ORGINCHANNELID = #{record.orginchannelid,jdbcType=VARCHAR}");
        }
        
        if (record.getSource() != null) {
            SET("SOURCE = #{record.source,jdbcType=CHAR}");
        }
        
        if (record.getSeatcode() != null) {
            SET("SEATCODE = #{record.seatcode,jdbcType=VARCHAR}");
        }
        
        if (record.getSecuritiesaccountid() != null) {
            SET("SECURITIESACCOUNTID = #{record.securitiesaccountid,jdbcType=VARCHAR}");
        }
        
        if (record.getRejectmsg() != null) {
            SET("REJECTMSG = #{record.rejectmsg,jdbcType=VARCHAR}");
        }
        
        if (record.getIsreedom() != null) {
            SET("ISREEDOM = #{record.isreedom,jdbcType=CHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("APP_TRANS");
        
        SET("DISTRIBUTORCODE = #{record.distributorcode,jdbcType=CHAR}");
        SET("APPSHEETSERIALNO = #{record.appsheetserialno,jdbcType=VARCHAR}");
        SET("IODATE = #{record.iodate,jdbcType=CHAR}");
        SET("SNO = #{record.sno,jdbcType=DECIMAL}");
        SET("RETURNMSG = #{record.returnmsg,jdbcType=VARCHAR}");
        SET("RETURNCODE = #{record.returncode,jdbcType=CHAR}");
        SET("TANO = #{record.tano,jdbcType=CHAR}");
        SET("TRANSACTIONCFMDATE = #{record.transactioncfmdate,jdbcType=CHAR}");
        SET("TASERIALNO = #{record.taserialno,jdbcType=VARCHAR}");
        SET("BUSINESSCODE = #{record.businesscode,jdbcType=CHAR}");
        SET("BUSINESSCODE_APP = #{record.businesscodeApp,jdbcType=CHAR}");
        SET("CUSTNO = #{record.custno,jdbcType=DECIMAL}");
        SET("CUSTTP = #{record.custtp,jdbcType=CHAR}");
        SET("CUSTFULLNAME = #{record.custfullname,jdbcType=VARCHAR}");
        SET("CUSTGROUP = #{record.custgroup,jdbcType=CHAR}");
        SET("CUSTCLASS1 = #{record.custclass1,jdbcType=VARCHAR}");
        SET("CUSTCLASS2 = #{record.custclass2,jdbcType=VARCHAR}");
        SET("TAACCOUNTID = #{record.taaccountid,jdbcType=CHAR}");
        SET("TAACCOUNTID_APP = #{record.taaccountidApp,jdbcType=CHAR}");
        SET("TRANSACTIONDATE = #{record.transactiondate,jdbcType=CHAR}");
        SET("TRANSACTIONTIME = #{record.transactiontime,jdbcType=CHAR}");
        SET("OPERDATE = #{record.operdate,jdbcType=CHAR}");
        SET("OPERTIME = #{record.opertime,jdbcType=CHAR}");
        SET("TRANSACTIONACCOUNTID = #{record.transactionaccountid,jdbcType=VARCHAR}");
        SET("BRANCHCODE = #{record.branchcode,jdbcType=VARCHAR}");
        SET("FUNDCODE = #{record.fundcode,jdbcType=CHAR}");
        SET("SHARETYPE = #{record.sharetype,jdbcType=CHAR}");
        SET("CURRENCYTYPE = #{record.currencytype,jdbcType=CHAR}");
        SET("APPLICATIONVOL = #{record.applicationvol,jdbcType=DECIMAL}");
        SET("APPLICATIONAMOUNT = #{record.applicationamount,jdbcType=DECIMAL}");
        SET("ORIGINAPPLICATIONVOL = #{record.originapplicationvol,jdbcType=DECIMAL}");
        SET("ORIGINAPPLICATIONAMOUNT = #{record.originapplicationamount,jdbcType=DECIMAL}");
        SET("DISCOUNTRATE = #{record.discountrate,jdbcType=DECIMAL}");
        SET("ORIGINDISCOUNTRATE = #{record.origindiscountrate,jdbcType=DECIMAL}");
        SET("TARGETTAACCOUNTID = #{record.targettaaccountid,jdbcType=CHAR}");
        SET("TARGETDISTRIBUTORCODE = #{record.targetdistributorcode,jdbcType=CHAR}");
        SET("TARGETTRANSACTIONACCOUNTID = #{record.targettransactionaccountid,jdbcType=VARCHAR}");
        SET("TARGETBRANCHCODE = #{record.targetbranchcode,jdbcType=VARCHAR}");
        SET("TARGETREGIONCODE = #{record.targetregioncode,jdbcType=CHAR}");
        SET("TARGETFUNDCODE = #{record.targetfundcode,jdbcType=CHAR}");
        SET("TARGETSHARETYPE = #{record.targetsharetype,jdbcType=CHAR}");
        SET("UPLOADDATE = #{record.uploaddate,jdbcType=CHAR}");
        SET("ORIGINALSERIALNO = #{record.originalserialno,jdbcType=VARCHAR}");
        SET("ORIGINALCFMDATE = #{record.originalcfmdate,jdbcType=CHAR}");
        SET("ORIGINALAPPSHEETNO = #{record.originalappsheetno,jdbcType=VARCHAR}");
        SET("ORIGINALAPPDATE = #{record.originalappdate,jdbcType=CHAR}");
        SET("ORIGINALSUBSDATE = #{record.originalsubsdate,jdbcType=CHAR}");
        SET("INVTP = #{record.invtp,jdbcType=CHAR}");
        SET("REGIONCODE = #{record.regioncode,jdbcType=CHAR}");
        SET("DEPOSITACCT = #{record.depositacct,jdbcType=VARCHAR}");
        SET("SHARECLASS = #{record.shareclass,jdbcType=CHAR}");
        SET("VALIDPERIOD = #{record.validperiod,jdbcType=DECIMAL}");
        SET("DEFDIVIDENDMETHOD = #{record.defdividendmethod,jdbcType=CHAR}");
        SET("DIVIDENDRATIO = #{record.dividendratio,jdbcType=DECIMAL}");
        SET("FUTUREBUYDATE = #{record.futurebuydate,jdbcType=CHAR}");
        SET("CONTRACTNO = #{record.contractno,jdbcType=VARCHAR}");
        SET("PROTOCOLNO = #{record.protocolno,jdbcType=VARCHAR}");
        SET("BEGINDATEOFPERIODICSUBS = #{record.begindateofperiodicsubs,jdbcType=CHAR}");
        SET("ENDDATEOFPERIODICSUBS = #{record.enddateofperiodicsubs,jdbcType=CHAR}");
        SET("PROTOCALENDDATE = #{record.protocalenddate,jdbcType=CHAR}");
        SET("DATEOFPERIODICSUBS = #{record.dateofperiodicsubs,jdbcType=CHAR}");
        SET("RATIONTERM = #{record.rationterm,jdbcType=VARCHAR}");
        SET("RATIONDATE = #{record.rationdate,jdbcType=DECIMAL}");
        SET("SAVEPLANFLAG = #{record.saveplanflag,jdbcType=CHAR}");
        SET("REGISTERDATE = #{record.registerdate,jdbcType=CHAR}");
        SET("SPECIFYREDEEMFLAG = #{record.specifyredeemflag,jdbcType=CHAR}");
        SET("REDEMPTIONINADVANCEFLAG = #{record.redemptioninadvanceflag,jdbcType=CHAR}");
        SET("REDEMPTIONDATEINADVANCE = #{record.redemptiondateinadvance,jdbcType=CHAR}");
        SET("DAYSREDEMPTIONINADVANCE = #{record.daysredemptioninadvance,jdbcType=DECIMAL}");
        SET("REDEMPTIONREASON = #{record.redemptionreason,jdbcType=CHAR}");
        SET("LARGEREDEMPTIONFLAG = #{record.largeredemptionflag,jdbcType=CHAR}");
        SET("FROZENCAUSE = #{record.frozencause,jdbcType=CHAR}");
        SET("FREEZINGDEADLINE = #{record.freezingdeadline,jdbcType=CHAR}");
        SET("CHARGE = #{record.charge,jdbcType=DECIMAL}");
        SET("HAVEMATCHQTY = #{record.havematchqty,jdbcType=DECIMAL}");
        SET("TOTALBACKENDLOAD = #{record.totalbackendload,jdbcType=DECIMAL}");
        SET("DETAILFLAG = #{record.detailflag,jdbcType=CHAR}");
        SET("SPECIFICATION = #{record.specification,jdbcType=VARCHAR}");
        SET("FROMTAFLAG = #{record.fromtaflag,jdbcType=CHAR}");
        SET("MONEYACCOUNT = #{record.moneyaccount,jdbcType=DECIMAL}");
        SET("CENTERNO = #{record.centerno,jdbcType=VARCHAR}");
        SET("NETNO = #{record.netno,jdbcType=VARCHAR}");
        SET("CHANNELID = #{record.channelid,jdbcType=VARCHAR}");
        SET("PAYCENTERID = #{record.paycenterid,jdbcType=VARCHAR}");
        SET("CUSTMANAGERID = #{record.custmanagerid,jdbcType=VARCHAR}");
        SET("FINANCINGMANAGERID = #{record.financingmanagerid,jdbcType=VARCHAR}");
        SET("REFERRAL = #{record.referral,jdbcType=VARCHAR}");
        SET("REFERRALPROV = #{record.referralprov,jdbcType=VARCHAR}");
        SET("REFERRALCITY = #{record.referralcity,jdbcType=VARCHAR}");
        SET("REFERRALMOBILE = #{record.referralmobile,jdbcType=VARCHAR}");
        SET("SALESPROMOTION = #{record.salespromotion,jdbcType=VARCHAR}");
        SET("OPERID = #{record.operid,jdbcType=VARCHAR}");
        SET("NETADDR = #{record.netaddr,jdbcType=VARCHAR}");
        SET("CANCELFLAG = #{record.cancelflag,jdbcType=CHAR}");
        SET("PRESTATUS = #{record.prestatus,jdbcType=CHAR}");
        SET("PAYSTATUS = #{record.paystatus,jdbcType=CHAR}");
        SET("STATUS = #{record.status,jdbcType=CHAR}");
        SET("LAST_STATUS = #{record.lastStatus,jdbcType=CHAR}");
        SET("RISKMATCHING = #{record.riskmatching,jdbcType=CHAR}");
        SET("ORDERFLAG = #{record.orderflag,jdbcType=CHAR}");
        SET("EXCEPTIONALFLAG = #{record.exceptionalflag,jdbcType=CHAR}");
        SET("OPERWAY = #{record.operway,jdbcType=CHAR}");
        SET("OPERORG = #{record.operorg,jdbcType=VARCHAR}");
        SET("BUSINESSKIND = #{record.businesskind,jdbcType=CHAR}");
        SET("TRANSACTORCERTTYPE = #{record.transactorcerttype,jdbcType=CHAR}");
        SET("TRANSACTORCERTNO = #{record.transactorcertno,jdbcType=VARCHAR}");
        SET("TRANSACTORNAME = #{record.transactorname,jdbcType=VARCHAR}");
        SET("ACCEPTMETHOD = #{record.acceptmethod,jdbcType=CHAR}");
        SET("TRANSACTORIDSTR = #{record.transactoridstr,jdbcType=VARCHAR}");
        SET("TRANSACTORNAMESTR = #{record.transactornamestr,jdbcType=VARCHAR}");
        SET("PAYTYPE = #{record.paytype,jdbcType=CHAR}");
        SET("ORGINCHANNELID = #{record.orginchannelid,jdbcType=VARCHAR}");
        SET("SOURCE = #{record.source,jdbcType=CHAR}");
        SET("SEATCODE = #{record.seatcode,jdbcType=VARCHAR}");
        SET("SECURITIESACCOUNTID = #{record.securitiesaccountid,jdbcType=VARCHAR}");
        SET("REJECTMSG = #{record.rejectmsg,jdbcType=VARCHAR}");
        SET("ISREEDOM = #{record.isreedom,jdbcType=CHAR}");
        
        kfatExample example = (kfatExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(kfat record) {
        BEGIN();
        UPDATE("APP_TRANS");
        
        if (record.getIodate() != null) {
            SET("IODATE = #{iodate,jdbcType=CHAR}");
        }
        
        if (record.getSno() != null) {
            SET("SNO = #{sno,jdbcType=DECIMAL}");
        }
        
        if (record.getReturnmsg() != null) {
            SET("RETURNMSG = #{returnmsg,jdbcType=VARCHAR}");
        }
        
        if (record.getReturncode() != null) {
            SET("RETURNCODE = #{returncode,jdbcType=CHAR}");
        }
        
        if (record.getTano() != null) {
            SET("TANO = #{tano,jdbcType=CHAR}");
        }
        
        if (record.getTransactioncfmdate() != null) {
            SET("TRANSACTIONCFMDATE = #{transactioncfmdate,jdbcType=CHAR}");
        }
        
        if (record.getTaserialno() != null) {
            SET("TASERIALNO = #{taserialno,jdbcType=VARCHAR}");
        }
        
        if (record.getBusinesscode() != null) {
            SET("BUSINESSCODE = #{businesscode,jdbcType=CHAR}");
        }
        
        if (record.getBusinesscodeApp() != null) {
            SET("BUSINESSCODE_APP = #{businesscodeApp,jdbcType=CHAR}");
        }
        
        if (record.getCustno() != null) {
            SET("CUSTNO = #{custno,jdbcType=DECIMAL}");
        }
        
        if (record.getCusttp() != null) {
            SET("CUSTTP = #{custtp,jdbcType=CHAR}");
        }
        
        if (record.getCustfullname() != null) {
            SET("CUSTFULLNAME = #{custfullname,jdbcType=VARCHAR}");
        }
        
        if (record.getCustgroup() != null) {
            SET("CUSTGROUP = #{custgroup,jdbcType=CHAR}");
        }
        
        if (record.getCustclass1() != null) {
            SET("CUSTCLASS1 = #{custclass1,jdbcType=VARCHAR}");
        }
        
        if (record.getCustclass2() != null) {
            SET("CUSTCLASS2 = #{custclass2,jdbcType=VARCHAR}");
        }
        
        if (record.getTaaccountid() != null) {
            SET("TAACCOUNTID = #{taaccountid,jdbcType=CHAR}");
        }
        
        if (record.getTaaccountidApp() != null) {
            SET("TAACCOUNTID_APP = #{taaccountidApp,jdbcType=CHAR}");
        }
        
        if (record.getTransactiondate() != null) {
            SET("TRANSACTIONDATE = #{transactiondate,jdbcType=CHAR}");
        }
        
        if (record.getTransactiontime() != null) {
            SET("TRANSACTIONTIME = #{transactiontime,jdbcType=CHAR}");
        }
        
        if (record.getOperdate() != null) {
            SET("OPERDATE = #{operdate,jdbcType=CHAR}");
        }
        
        if (record.getOpertime() != null) {
            SET("OPERTIME = #{opertime,jdbcType=CHAR}");
        }
        
        if (record.getTransactionaccountid() != null) {
            SET("TRANSACTIONACCOUNTID = #{transactionaccountid,jdbcType=VARCHAR}");
        }
        
        if (record.getBranchcode() != null) {
            SET("BRANCHCODE = #{branchcode,jdbcType=VARCHAR}");
        }
        
        if (record.getFundcode() != null) {
            SET("FUNDCODE = #{fundcode,jdbcType=CHAR}");
        }
        
        if (record.getSharetype() != null) {
            SET("SHARETYPE = #{sharetype,jdbcType=CHAR}");
        }
        
        if (record.getCurrencytype() != null) {
            SET("CURRENCYTYPE = #{currencytype,jdbcType=CHAR}");
        }
        
        if (record.getApplicationvol() != null) {
            SET("APPLICATIONVOL = #{applicationvol,jdbcType=DECIMAL}");
        }
        
        if (record.getApplicationamount() != null) {
            SET("APPLICATIONAMOUNT = #{applicationamount,jdbcType=DECIMAL}");
        }
        
        if (record.getOriginapplicationvol() != null) {
            SET("ORIGINAPPLICATIONVOL = #{originapplicationvol,jdbcType=DECIMAL}");
        }
        
        if (record.getOriginapplicationamount() != null) {
            SET("ORIGINAPPLICATIONAMOUNT = #{originapplicationamount,jdbcType=DECIMAL}");
        }
        
        if (record.getDiscountrate() != null) {
            SET("DISCOUNTRATE = #{discountrate,jdbcType=DECIMAL}");
        }
        
        if (record.getOrigindiscountrate() != null) {
            SET("ORIGINDISCOUNTRATE = #{origindiscountrate,jdbcType=DECIMAL}");
        }
        
        if (record.getTargettaaccountid() != null) {
            SET("TARGETTAACCOUNTID = #{targettaaccountid,jdbcType=CHAR}");
        }
        
        if (record.getTargetdistributorcode() != null) {
            SET("TARGETDISTRIBUTORCODE = #{targetdistributorcode,jdbcType=CHAR}");
        }
        
        if (record.getTargettransactionaccountid() != null) {
            SET("TARGETTRANSACTIONACCOUNTID = #{targettransactionaccountid,jdbcType=VARCHAR}");
        }
        
        if (record.getTargetbranchcode() != null) {
            SET("TARGETBRANCHCODE = #{targetbranchcode,jdbcType=VARCHAR}");
        }
        
        if (record.getTargetregioncode() != null) {
            SET("TARGETREGIONCODE = #{targetregioncode,jdbcType=CHAR}");
        }
        
        if (record.getTargetfundcode() != null) {
            SET("TARGETFUNDCODE = #{targetfundcode,jdbcType=CHAR}");
        }
        
        if (record.getTargetsharetype() != null) {
            SET("TARGETSHARETYPE = #{targetsharetype,jdbcType=CHAR}");
        }
        
        if (record.getUploaddate() != null) {
            SET("UPLOADDATE = #{uploaddate,jdbcType=CHAR}");
        }
        
        if (record.getOriginalserialno() != null) {
            SET("ORIGINALSERIALNO = #{originalserialno,jdbcType=VARCHAR}");
        }
        
        if (record.getOriginalcfmdate() != null) {
            SET("ORIGINALCFMDATE = #{originalcfmdate,jdbcType=CHAR}");
        }
        
        if (record.getOriginalappsheetno() != null) {
            SET("ORIGINALAPPSHEETNO = #{originalappsheetno,jdbcType=VARCHAR}");
        }
        
        if (record.getOriginalappdate() != null) {
            SET("ORIGINALAPPDATE = #{originalappdate,jdbcType=CHAR}");
        }
        
        if (record.getOriginalsubsdate() != null) {
            SET("ORIGINALSUBSDATE = #{originalsubsdate,jdbcType=CHAR}");
        }
        
        if (record.getInvtp() != null) {
            SET("INVTP = #{invtp,jdbcType=CHAR}");
        }
        
        if (record.getRegioncode() != null) {
            SET("REGIONCODE = #{regioncode,jdbcType=CHAR}");
        }
        
        if (record.getDepositacct() != null) {
            SET("DEPOSITACCT = #{depositacct,jdbcType=VARCHAR}");
        }
        
        if (record.getShareclass() != null) {
            SET("SHARECLASS = #{shareclass,jdbcType=CHAR}");
        }
        
        if (record.getValidperiod() != null) {
            SET("VALIDPERIOD = #{validperiod,jdbcType=DECIMAL}");
        }
        
        if (record.getDefdividendmethod() != null) {
            SET("DEFDIVIDENDMETHOD = #{defdividendmethod,jdbcType=CHAR}");
        }
        
        if (record.getDividendratio() != null) {
            SET("DIVIDENDRATIO = #{dividendratio,jdbcType=DECIMAL}");
        }
        
        if (record.getFuturebuydate() != null) {
            SET("FUTUREBUYDATE = #{futurebuydate,jdbcType=CHAR}");
        }
        
        if (record.getContractno() != null) {
            SET("CONTRACTNO = #{contractno,jdbcType=VARCHAR}");
        }
        
        if (record.getProtocolno() != null) {
            SET("PROTOCOLNO = #{protocolno,jdbcType=VARCHAR}");
        }
        
        if (record.getBegindateofperiodicsubs() != null) {
            SET("BEGINDATEOFPERIODICSUBS = #{begindateofperiodicsubs,jdbcType=CHAR}");
        }
        
        if (record.getEnddateofperiodicsubs() != null) {
            SET("ENDDATEOFPERIODICSUBS = #{enddateofperiodicsubs,jdbcType=CHAR}");
        }
        
        if (record.getProtocalenddate() != null) {
            SET("PROTOCALENDDATE = #{protocalenddate,jdbcType=CHAR}");
        }
        
        if (record.getDateofperiodicsubs() != null) {
            SET("DATEOFPERIODICSUBS = #{dateofperiodicsubs,jdbcType=CHAR}");
        }
        
        if (record.getRationterm() != null) {
            SET("RATIONTERM = #{rationterm,jdbcType=VARCHAR}");
        }
        
        if (record.getRationdate() != null) {
            SET("RATIONDATE = #{rationdate,jdbcType=DECIMAL}");
        }
        
        if (record.getSaveplanflag() != null) {
            SET("SAVEPLANFLAG = #{saveplanflag,jdbcType=CHAR}");
        }
        
        if (record.getRegisterdate() != null) {
            SET("REGISTERDATE = #{registerdate,jdbcType=CHAR}");
        }
        
        if (record.getSpecifyredeemflag() != null) {
            SET("SPECIFYREDEEMFLAG = #{specifyredeemflag,jdbcType=CHAR}");
        }
        
        if (record.getRedemptioninadvanceflag() != null) {
            SET("REDEMPTIONINADVANCEFLAG = #{redemptioninadvanceflag,jdbcType=CHAR}");
        }
        
        if (record.getRedemptiondateinadvance() != null) {
            SET("REDEMPTIONDATEINADVANCE = #{redemptiondateinadvance,jdbcType=CHAR}");
        }
        
        if (record.getDaysredemptioninadvance() != null) {
            SET("DAYSREDEMPTIONINADVANCE = #{daysredemptioninadvance,jdbcType=DECIMAL}");
        }
        
        if (record.getRedemptionreason() != null) {
            SET("REDEMPTIONREASON = #{redemptionreason,jdbcType=CHAR}");
        }
        
        if (record.getLargeredemptionflag() != null) {
            SET("LARGEREDEMPTIONFLAG = #{largeredemptionflag,jdbcType=CHAR}");
        }
        
        if (record.getFrozencause() != null) {
            SET("FROZENCAUSE = #{frozencause,jdbcType=CHAR}");
        }
        
        if (record.getFreezingdeadline() != null) {
            SET("FREEZINGDEADLINE = #{freezingdeadline,jdbcType=CHAR}");
        }
        
        if (record.getCharge() != null) {
            SET("CHARGE = #{charge,jdbcType=DECIMAL}");
        }
        
        if (record.getHavematchqty() != null) {
            SET("HAVEMATCHQTY = #{havematchqty,jdbcType=DECIMAL}");
        }
        
        if (record.getTotalbackendload() != null) {
            SET("TOTALBACKENDLOAD = #{totalbackendload,jdbcType=DECIMAL}");
        }
        
        if (record.getDetailflag() != null) {
            SET("DETAILFLAG = #{detailflag,jdbcType=CHAR}");
        }
        
        if (record.getSpecification() != null) {
            SET("SPECIFICATION = #{specification,jdbcType=VARCHAR}");
        }
        
        if (record.getFromtaflag() != null) {
            SET("FROMTAFLAG = #{fromtaflag,jdbcType=CHAR}");
        }
        
        if (record.getMoneyaccount() != null) {
            SET("MONEYACCOUNT = #{moneyaccount,jdbcType=DECIMAL}");
        }
        
        if (record.getCenterno() != null) {
            SET("CENTERNO = #{centerno,jdbcType=VARCHAR}");
        }
        
        if (record.getNetno() != null) {
            SET("NETNO = #{netno,jdbcType=VARCHAR}");
        }
        
        if (record.getChannelid() != null) {
            SET("CHANNELID = #{channelid,jdbcType=VARCHAR}");
        }
        
        if (record.getPaycenterid() != null) {
            SET("PAYCENTERID = #{paycenterid,jdbcType=VARCHAR}");
        }
        
        if (record.getCustmanagerid() != null) {
            SET("CUSTMANAGERID = #{custmanagerid,jdbcType=VARCHAR}");
        }
        
        if (record.getFinancingmanagerid() != null) {
            SET("FINANCINGMANAGERID = #{financingmanagerid,jdbcType=VARCHAR}");
        }
        
        if (record.getReferral() != null) {
            SET("REFERRAL = #{referral,jdbcType=VARCHAR}");
        }
        
        if (record.getReferralprov() != null) {
            SET("REFERRALPROV = #{referralprov,jdbcType=VARCHAR}");
        }
        
        if (record.getReferralcity() != null) {
            SET("REFERRALCITY = #{referralcity,jdbcType=VARCHAR}");
        }
        
        if (record.getReferralmobile() != null) {
            SET("REFERRALMOBILE = #{referralmobile,jdbcType=VARCHAR}");
        }
        
        if (record.getSalespromotion() != null) {
            SET("SALESPROMOTION = #{salespromotion,jdbcType=VARCHAR}");
        }
        
        if (record.getOperid() != null) {
            SET("OPERID = #{operid,jdbcType=VARCHAR}");
        }
        
        if (record.getNetaddr() != null) {
            SET("NETADDR = #{netaddr,jdbcType=VARCHAR}");
        }
        
        if (record.getCancelflag() != null) {
            SET("CANCELFLAG = #{cancelflag,jdbcType=CHAR}");
        }
        
        if (record.getPrestatus() != null) {
            SET("PRESTATUS = #{prestatus,jdbcType=CHAR}");
        }
        
        if (record.getPaystatus() != null) {
            SET("PAYSTATUS = #{paystatus,jdbcType=CHAR}");
        }
        
        if (record.getStatus() != null) {
            SET("STATUS = #{status,jdbcType=CHAR}");
        }
        
        if (record.getLastStatus() != null) {
            SET("LAST_STATUS = #{lastStatus,jdbcType=CHAR}");
        }
        
        if (record.getRiskmatching() != null) {
            SET("RISKMATCHING = #{riskmatching,jdbcType=CHAR}");
        }
        
        if (record.getOrderflag() != null) {
            SET("ORDERFLAG = #{orderflag,jdbcType=CHAR}");
        }
        
        if (record.getExceptionalflag() != null) {
            SET("EXCEPTIONALFLAG = #{exceptionalflag,jdbcType=CHAR}");
        }
        
        if (record.getOperway() != null) {
            SET("OPERWAY = #{operway,jdbcType=CHAR}");
        }
        
        if (record.getOperorg() != null) {
            SET("OPERORG = #{operorg,jdbcType=VARCHAR}");
        }
        
        if (record.getBusinesskind() != null) {
            SET("BUSINESSKIND = #{businesskind,jdbcType=CHAR}");
        }
        
        if (record.getTransactorcerttype() != null) {
            SET("TRANSACTORCERTTYPE = #{transactorcerttype,jdbcType=CHAR}");
        }
        
        if (record.getTransactorcertno() != null) {
            SET("TRANSACTORCERTNO = #{transactorcertno,jdbcType=VARCHAR}");
        }
        
        if (record.getTransactorname() != null) {
            SET("TRANSACTORNAME = #{transactorname,jdbcType=VARCHAR}");
        }
        
        if (record.getAcceptmethod() != null) {
            SET("ACCEPTMETHOD = #{acceptmethod,jdbcType=CHAR}");
        }
        
        if (record.getTransactoridstr() != null) {
            SET("TRANSACTORIDSTR = #{transactoridstr,jdbcType=VARCHAR}");
        }
        
        if (record.getTransactornamestr() != null) {
            SET("TRANSACTORNAMESTR = #{transactornamestr,jdbcType=VARCHAR}");
        }
        
        if (record.getPaytype() != null) {
            SET("PAYTYPE = #{paytype,jdbcType=CHAR}");
        }
        
        if (record.getOrginchannelid() != null) {
            SET("ORGINCHANNELID = #{orginchannelid,jdbcType=VARCHAR}");
        }
        
        if (record.getSource() != null) {
            SET("SOURCE = #{source,jdbcType=CHAR}");
        }
        
        if (record.getSeatcode() != null) {
            SET("SEATCODE = #{seatcode,jdbcType=VARCHAR}");
        }
        
        if (record.getSecuritiesaccountid() != null) {
            SET("SECURITIESACCOUNTID = #{securitiesaccountid,jdbcType=VARCHAR}");
        }
        
        if (record.getRejectmsg() != null) {
            SET("REJECTMSG = #{rejectmsg,jdbcType=VARCHAR}");
        }
        
        if (record.getIsreedom() != null) {
            SET("ISREEDOM = #{isreedom,jdbcType=CHAR}");
        }
        
        WHERE("DISTRIBUTORCODE = #{distributorcode,jdbcType=CHAR}");
        WHERE("APPSHEETSERIALNO = #{appsheetserialno,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    protected void applyWhere(kfatExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}