package test;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import test.kfat;
import test.kfatExample;
import test.kfatKey;

public interface kfatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @SelectProvider(type=kfatSqlProvider.class, method="countByExample")
    int countByExample(kfatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @DeleteProvider(type=kfatSqlProvider.class, method="deleteByExample")
    int deleteByExample(kfatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @Delete({
        "delete from APP_TRANS",
        "where DISTRIBUTORCODE = #{distributorcode,jdbcType=CHAR}",
          "and APPSHEETSERIALNO = #{appsheetserialno,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(kfatKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @Insert({
        "insert into APP_TRANS (DISTRIBUTORCODE, APPSHEETSERIALNO, ",
        "IODATE, SNO, RETURNMSG, ",
        "RETURNCODE, TANO, TRANSACTIONCFMDATE, ",
        "TASERIALNO, BUSINESSCODE, ",
        "BUSINESSCODE_APP, CUSTNO, ",
        "CUSTTP, CUSTFULLNAME, ",
        "CUSTGROUP, CUSTCLASS1, ",
        "CUSTCLASS2, TAACCOUNTID, ",
        "TAACCOUNTID_APP, TRANSACTIONDATE, ",
        "TRANSACTIONTIME, OPERDATE, ",
        "OPERTIME, TRANSACTIONACCOUNTID, ",
        "BRANCHCODE, FUNDCODE, ",
        "SHARETYPE, CURRENCYTYPE, ",
        "APPLICATIONVOL, APPLICATIONAMOUNT, ",
        "ORIGINAPPLICATIONVOL, ORIGINAPPLICATIONAMOUNT, ",
        "DISCOUNTRATE, ORIGINDISCOUNTRATE, ",
        "TARGETTAACCOUNTID, TARGETDISTRIBUTORCODE, ",
        "TARGETTRANSACTIONACCOUNTID, TARGETBRANCHCODE, ",
        "TARGETREGIONCODE, TARGETFUNDCODE, ",
        "TARGETSHARETYPE, UPLOADDATE, ",
        "ORIGINALSERIALNO, ORIGINALCFMDATE, ",
        "ORIGINALAPPSHEETNO, ORIGINALAPPDATE, ",
        "ORIGINALSUBSDATE, INVTP, ",
        "REGIONCODE, DEPOSITACCT, ",
        "SHARECLASS, VALIDPERIOD, ",
        "DEFDIVIDENDMETHOD, DIVIDENDRATIO, ",
        "FUTUREBUYDATE, CONTRACTNO, ",
        "PROTOCOLNO, BEGINDATEOFPERIODICSUBS, ",
        "ENDDATEOFPERIODICSUBS, PROTOCALENDDATE, ",
        "DATEOFPERIODICSUBS, RATIONTERM, ",
        "RATIONDATE, SAVEPLANFLAG, ",
        "REGISTERDATE, SPECIFYREDEEMFLAG, ",
        "REDEMPTIONINADVANCEFLAG, REDEMPTIONDATEINADVANCE, ",
        "DAYSREDEMPTIONINADVANCE, REDEMPTIONREASON, ",
        "LARGEREDEMPTIONFLAG, FROZENCAUSE, ",
        "FREEZINGDEADLINE, CHARGE, ",
        "HAVEMATCHQTY, TOTALBACKENDLOAD, ",
        "DETAILFLAG, SPECIFICATION, ",
        "FROMTAFLAG, MONEYACCOUNT, ",
        "CENTERNO, NETNO, ",
        "CHANNELID, PAYCENTERID, ",
        "CUSTMANAGERID, FINANCINGMANAGERID, ",
        "REFERRAL, REFERRALPROV, ",
        "REFERRALCITY, REFERRALMOBILE, ",
        "SALESPROMOTION, OPERID, ",
        "NETADDR, CANCELFLAG, ",
        "PRESTATUS, PAYSTATUS, ",
        "STATUS, LAST_STATUS, RISKMATCHING, ",
        "ORDERFLAG, EXCEPTIONALFLAG, ",
        "OPERWAY, OPERORG, BUSINESSKIND, ",
        "TRANSACTORCERTTYPE, TRANSACTORCERTNO, ",
        "TRANSACTORNAME, ACCEPTMETHOD, ",
        "TRANSACTORIDSTR, TRANSACTORNAMESTR, ",
        "PAYTYPE, ORGINCHANNELID, ",
        "SOURCE, SEATCODE, SECURITIESACCOUNTID, ",
        "REJECTMSG, ISREEDOM)",
        "values (#{distributorcode,jdbcType=CHAR}, #{appsheetserialno,jdbcType=VARCHAR}, ",
        "#{iodate,jdbcType=CHAR}, #{sno,jdbcType=DECIMAL}, #{returnmsg,jdbcType=VARCHAR}, ",
        "#{returncode,jdbcType=CHAR}, #{tano,jdbcType=CHAR}, #{transactioncfmdate,jdbcType=CHAR}, ",
        "#{taserialno,jdbcType=VARCHAR}, #{businesscode,jdbcType=CHAR}, ",
        "#{businesscodeApp,jdbcType=CHAR}, #{custno,jdbcType=DECIMAL}, ",
        "#{custtp,jdbcType=CHAR}, #{custfullname,jdbcType=VARCHAR}, ",
        "#{custgroup,jdbcType=CHAR}, #{custclass1,jdbcType=VARCHAR}, ",
        "#{custclass2,jdbcType=VARCHAR}, #{taaccountid,jdbcType=CHAR}, ",
        "#{taaccountidApp,jdbcType=CHAR}, #{transactiondate,jdbcType=CHAR}, ",
        "#{transactiontime,jdbcType=CHAR}, #{operdate,jdbcType=CHAR}, ",
        "#{opertime,jdbcType=CHAR}, #{transactionaccountid,jdbcType=VARCHAR}, ",
        "#{branchcode,jdbcType=VARCHAR}, #{fundcode,jdbcType=CHAR}, ",
        "#{sharetype,jdbcType=CHAR}, #{currencytype,jdbcType=CHAR}, ",
        "#{applicationvol,jdbcType=DECIMAL}, #{applicationamount,jdbcType=DECIMAL}, ",
        "#{originapplicationvol,jdbcType=DECIMAL}, #{originapplicationamount,jdbcType=DECIMAL}, ",
        "#{discountrate,jdbcType=DECIMAL}, #{origindiscountrate,jdbcType=DECIMAL}, ",
        "#{targettaaccountid,jdbcType=CHAR}, #{targetdistributorcode,jdbcType=CHAR}, ",
        "#{targettransactionaccountid,jdbcType=VARCHAR}, #{targetbranchcode,jdbcType=VARCHAR}, ",
        "#{targetregioncode,jdbcType=CHAR}, #{targetfundcode,jdbcType=CHAR}, ",
        "#{targetsharetype,jdbcType=CHAR}, #{uploaddate,jdbcType=CHAR}, ",
        "#{originalserialno,jdbcType=VARCHAR}, #{originalcfmdate,jdbcType=CHAR}, ",
        "#{originalappsheetno,jdbcType=VARCHAR}, #{originalappdate,jdbcType=CHAR}, ",
        "#{originalsubsdate,jdbcType=CHAR}, #{invtp,jdbcType=CHAR}, ",
        "#{regioncode,jdbcType=CHAR}, #{depositacct,jdbcType=VARCHAR}, ",
        "#{shareclass,jdbcType=CHAR}, #{validperiod,jdbcType=DECIMAL}, ",
        "#{defdividendmethod,jdbcType=CHAR}, #{dividendratio,jdbcType=DECIMAL}, ",
        "#{futurebuydate,jdbcType=CHAR}, #{contractno,jdbcType=VARCHAR}, ",
        "#{protocolno,jdbcType=VARCHAR}, #{begindateofperiodicsubs,jdbcType=CHAR}, ",
        "#{enddateofperiodicsubs,jdbcType=CHAR}, #{protocalenddate,jdbcType=CHAR}, ",
        "#{dateofperiodicsubs,jdbcType=CHAR}, #{rationterm,jdbcType=VARCHAR}, ",
        "#{rationdate,jdbcType=DECIMAL}, #{saveplanflag,jdbcType=CHAR}, ",
        "#{registerdate,jdbcType=CHAR}, #{specifyredeemflag,jdbcType=CHAR}, ",
        "#{redemptioninadvanceflag,jdbcType=CHAR}, #{redemptiondateinadvance,jdbcType=CHAR}, ",
        "#{daysredemptioninadvance,jdbcType=DECIMAL}, #{redemptionreason,jdbcType=CHAR}, ",
        "#{largeredemptionflag,jdbcType=CHAR}, #{frozencause,jdbcType=CHAR}, ",
        "#{freezingdeadline,jdbcType=CHAR}, #{charge,jdbcType=DECIMAL}, ",
        "#{havematchqty,jdbcType=DECIMAL}, #{totalbackendload,jdbcType=DECIMAL}, ",
        "#{detailflag,jdbcType=CHAR}, #{specification,jdbcType=VARCHAR}, ",
        "#{fromtaflag,jdbcType=CHAR}, #{moneyaccount,jdbcType=DECIMAL}, ",
        "#{centerno,jdbcType=VARCHAR}, #{netno,jdbcType=VARCHAR}, ",
        "#{channelid,jdbcType=VARCHAR}, #{paycenterid,jdbcType=VARCHAR}, ",
        "#{custmanagerid,jdbcType=VARCHAR}, #{financingmanagerid,jdbcType=VARCHAR}, ",
        "#{referral,jdbcType=VARCHAR}, #{referralprov,jdbcType=VARCHAR}, ",
        "#{referralcity,jdbcType=VARCHAR}, #{referralmobile,jdbcType=VARCHAR}, ",
        "#{salespromotion,jdbcType=VARCHAR}, #{operid,jdbcType=VARCHAR}, ",
        "#{netaddr,jdbcType=VARCHAR}, #{cancelflag,jdbcType=CHAR}, ",
        "#{prestatus,jdbcType=CHAR}, #{paystatus,jdbcType=CHAR}, ",
        "#{status,jdbcType=CHAR}, #{lastStatus,jdbcType=CHAR}, #{riskmatching,jdbcType=CHAR}, ",
        "#{orderflag,jdbcType=CHAR}, #{exceptionalflag,jdbcType=CHAR}, ",
        "#{operway,jdbcType=CHAR}, #{operorg,jdbcType=VARCHAR}, #{businesskind,jdbcType=CHAR}, ",
        "#{transactorcerttype,jdbcType=CHAR}, #{transactorcertno,jdbcType=VARCHAR}, ",
        "#{transactorname,jdbcType=VARCHAR}, #{acceptmethod,jdbcType=CHAR}, ",
        "#{transactoridstr,jdbcType=VARCHAR}, #{transactornamestr,jdbcType=VARCHAR}, ",
        "#{paytype,jdbcType=CHAR}, #{orginchannelid,jdbcType=VARCHAR}, ",
        "#{source,jdbcType=CHAR}, #{seatcode,jdbcType=VARCHAR}, #{securitiesaccountid,jdbcType=VARCHAR}, ",
        "#{rejectmsg,jdbcType=VARCHAR}, #{isreedom,jdbcType=CHAR})"
    })
    int insert(kfat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @InsertProvider(type=kfatSqlProvider.class, method="insertSelective")
    int insertSelective(kfat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @SelectProvider(type=kfatSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="DISTRIBUTORCODE", property="distributorcode", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="APPSHEETSERIALNO", property="appsheetserialno", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="IODATE", property="iodate", jdbcType=JdbcType.CHAR),
        @Result(column="SNO", property="sno", jdbcType=JdbcType.DECIMAL),
        @Result(column="RETURNMSG", property="returnmsg", jdbcType=JdbcType.VARCHAR),
        @Result(column="RETURNCODE", property="returncode", jdbcType=JdbcType.CHAR),
        @Result(column="TANO", property="tano", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSACTIONCFMDATE", property="transactioncfmdate", jdbcType=JdbcType.CHAR),
        @Result(column="TASERIALNO", property="taserialno", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESSCODE", property="businesscode", jdbcType=JdbcType.CHAR),
        @Result(column="BUSINESSCODE_APP", property="businesscodeApp", jdbcType=JdbcType.CHAR),
        @Result(column="CUSTNO", property="custno", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUSTTP", property="custtp", jdbcType=JdbcType.CHAR),
        @Result(column="CUSTFULLNAME", property="custfullname", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUSTGROUP", property="custgroup", jdbcType=JdbcType.CHAR),
        @Result(column="CUSTCLASS1", property="custclass1", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUSTCLASS2", property="custclass2", jdbcType=JdbcType.VARCHAR),
        @Result(column="TAACCOUNTID", property="taaccountid", jdbcType=JdbcType.CHAR),
        @Result(column="TAACCOUNTID_APP", property="taaccountidApp", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSACTIONDATE", property="transactiondate", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSACTIONTIME", property="transactiontime", jdbcType=JdbcType.CHAR),
        @Result(column="OPERDATE", property="operdate", jdbcType=JdbcType.CHAR),
        @Result(column="OPERTIME", property="opertime", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSACTIONACCOUNTID", property="transactionaccountid", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRANCHCODE", property="branchcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="FUNDCODE", property="fundcode", jdbcType=JdbcType.CHAR),
        @Result(column="SHARETYPE", property="sharetype", jdbcType=JdbcType.CHAR),
        @Result(column="CURRENCYTYPE", property="currencytype", jdbcType=JdbcType.CHAR),
        @Result(column="APPLICATIONVOL", property="applicationvol", jdbcType=JdbcType.DECIMAL),
        @Result(column="APPLICATIONAMOUNT", property="applicationamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORIGINAPPLICATIONVOL", property="originapplicationvol", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORIGINAPPLICATIONAMOUNT", property="originapplicationamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="DISCOUNTRATE", property="discountrate", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORIGINDISCOUNTRATE", property="origindiscountrate", jdbcType=JdbcType.DECIMAL),
        @Result(column="TARGETTAACCOUNTID", property="targettaaccountid", jdbcType=JdbcType.CHAR),
        @Result(column="TARGETDISTRIBUTORCODE", property="targetdistributorcode", jdbcType=JdbcType.CHAR),
        @Result(column="TARGETTRANSACTIONACCOUNTID", property="targettransactionaccountid", jdbcType=JdbcType.VARCHAR),
        @Result(column="TARGETBRANCHCODE", property="targetbranchcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="TARGETREGIONCODE", property="targetregioncode", jdbcType=JdbcType.CHAR),
        @Result(column="TARGETFUNDCODE", property="targetfundcode", jdbcType=JdbcType.CHAR),
        @Result(column="TARGETSHARETYPE", property="targetsharetype", jdbcType=JdbcType.CHAR),
        @Result(column="UPLOADDATE", property="uploaddate", jdbcType=JdbcType.CHAR),
        @Result(column="ORIGINALSERIALNO", property="originalserialno", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORIGINALCFMDATE", property="originalcfmdate", jdbcType=JdbcType.CHAR),
        @Result(column="ORIGINALAPPSHEETNO", property="originalappsheetno", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORIGINALAPPDATE", property="originalappdate", jdbcType=JdbcType.CHAR),
        @Result(column="ORIGINALSUBSDATE", property="originalsubsdate", jdbcType=JdbcType.CHAR),
        @Result(column="INVTP", property="invtp", jdbcType=JdbcType.CHAR),
        @Result(column="REGIONCODE", property="regioncode", jdbcType=JdbcType.CHAR),
        @Result(column="DEPOSITACCT", property="depositacct", jdbcType=JdbcType.VARCHAR),
        @Result(column="SHARECLASS", property="shareclass", jdbcType=JdbcType.CHAR),
        @Result(column="VALIDPERIOD", property="validperiod", jdbcType=JdbcType.DECIMAL),
        @Result(column="DEFDIVIDENDMETHOD", property="defdividendmethod", jdbcType=JdbcType.CHAR),
        @Result(column="DIVIDENDRATIO", property="dividendratio", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUTUREBUYDATE", property="futurebuydate", jdbcType=JdbcType.CHAR),
        @Result(column="CONTRACTNO", property="contractno", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROTOCOLNO", property="protocolno", jdbcType=JdbcType.VARCHAR),
        @Result(column="BEGINDATEOFPERIODICSUBS", property="begindateofperiodicsubs", jdbcType=JdbcType.CHAR),
        @Result(column="ENDDATEOFPERIODICSUBS", property="enddateofperiodicsubs", jdbcType=JdbcType.CHAR),
        @Result(column="PROTOCALENDDATE", property="protocalenddate", jdbcType=JdbcType.CHAR),
        @Result(column="DATEOFPERIODICSUBS", property="dateofperiodicsubs", jdbcType=JdbcType.CHAR),
        @Result(column="RATIONTERM", property="rationterm", jdbcType=JdbcType.VARCHAR),
        @Result(column="RATIONDATE", property="rationdate", jdbcType=JdbcType.DECIMAL),
        @Result(column="SAVEPLANFLAG", property="saveplanflag", jdbcType=JdbcType.CHAR),
        @Result(column="REGISTERDATE", property="registerdate", jdbcType=JdbcType.CHAR),
        @Result(column="SPECIFYREDEEMFLAG", property="specifyredeemflag", jdbcType=JdbcType.CHAR),
        @Result(column="REDEMPTIONINADVANCEFLAG", property="redemptioninadvanceflag", jdbcType=JdbcType.CHAR),
        @Result(column="REDEMPTIONDATEINADVANCE", property="redemptiondateinadvance", jdbcType=JdbcType.CHAR),
        @Result(column="DAYSREDEMPTIONINADVANCE", property="daysredemptioninadvance", jdbcType=JdbcType.DECIMAL),
        @Result(column="REDEMPTIONREASON", property="redemptionreason", jdbcType=JdbcType.CHAR),
        @Result(column="LARGEREDEMPTIONFLAG", property="largeredemptionflag", jdbcType=JdbcType.CHAR),
        @Result(column="FROZENCAUSE", property="frozencause", jdbcType=JdbcType.CHAR),
        @Result(column="FREEZINGDEADLINE", property="freezingdeadline", jdbcType=JdbcType.CHAR),
        @Result(column="CHARGE", property="charge", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAVEMATCHQTY", property="havematchqty", jdbcType=JdbcType.DECIMAL),
        @Result(column="TOTALBACKENDLOAD", property="totalbackendload", jdbcType=JdbcType.DECIMAL),
        @Result(column="DETAILFLAG", property="detailflag", jdbcType=JdbcType.CHAR),
        @Result(column="SPECIFICATION", property="specification", jdbcType=JdbcType.VARCHAR),
        @Result(column="FROMTAFLAG", property="fromtaflag", jdbcType=JdbcType.CHAR),
        @Result(column="MONEYACCOUNT", property="moneyaccount", jdbcType=JdbcType.DECIMAL),
        @Result(column="CENTERNO", property="centerno", jdbcType=JdbcType.VARCHAR),
        @Result(column="NETNO", property="netno", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHANNELID", property="channelid", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAYCENTERID", property="paycenterid", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUSTMANAGERID", property="custmanagerid", jdbcType=JdbcType.VARCHAR),
        @Result(column="FINANCINGMANAGERID", property="financingmanagerid", jdbcType=JdbcType.VARCHAR),
        @Result(column="REFERRAL", property="referral", jdbcType=JdbcType.VARCHAR),
        @Result(column="REFERRALPROV", property="referralprov", jdbcType=JdbcType.VARCHAR),
        @Result(column="REFERRALCITY", property="referralcity", jdbcType=JdbcType.VARCHAR),
        @Result(column="REFERRALMOBILE", property="referralmobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="SALESPROMOTION", property="salespromotion", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPERID", property="operid", jdbcType=JdbcType.VARCHAR),
        @Result(column="NETADDR", property="netaddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="CANCELFLAG", property="cancelflag", jdbcType=JdbcType.CHAR),
        @Result(column="PRESTATUS", property="prestatus", jdbcType=JdbcType.CHAR),
        @Result(column="PAYSTATUS", property="paystatus", jdbcType=JdbcType.CHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="LAST_STATUS", property="lastStatus", jdbcType=JdbcType.CHAR),
        @Result(column="RISKMATCHING", property="riskmatching", jdbcType=JdbcType.CHAR),
        @Result(column="ORDERFLAG", property="orderflag", jdbcType=JdbcType.CHAR),
        @Result(column="EXCEPTIONALFLAG", property="exceptionalflag", jdbcType=JdbcType.CHAR),
        @Result(column="OPERWAY", property="operway", jdbcType=JdbcType.CHAR),
        @Result(column="OPERORG", property="operorg", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESSKIND", property="businesskind", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSACTORCERTTYPE", property="transactorcerttype", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSACTORCERTNO", property="transactorcertno", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSACTORNAME", property="transactorname", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACCEPTMETHOD", property="acceptmethod", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSACTORIDSTR", property="transactoridstr", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSACTORNAMESTR", property="transactornamestr", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAYTYPE", property="paytype", jdbcType=JdbcType.CHAR),
        @Result(column="ORGINCHANNELID", property="orginchannelid", jdbcType=JdbcType.VARCHAR),
        @Result(column="SOURCE", property="source", jdbcType=JdbcType.CHAR),
        @Result(column="SEATCODE", property="seatcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="SECURITIESACCOUNTID", property="securitiesaccountid", jdbcType=JdbcType.VARCHAR),
        @Result(column="REJECTMSG", property="rejectmsg", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISREEDOM", property="isreedom", jdbcType=JdbcType.CHAR)
    })
    List<kfat> selectByExample(kfatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "DISTRIBUTORCODE, APPSHEETSERIALNO, IODATE, SNO, RETURNMSG, RETURNCODE, TANO, ",
        "TRANSACTIONCFMDATE, TASERIALNO, BUSINESSCODE, BUSINESSCODE_APP, CUSTNO, CUSTTP, ",
        "CUSTFULLNAME, CUSTGROUP, CUSTCLASS1, CUSTCLASS2, TAACCOUNTID, TAACCOUNTID_APP, ",
        "TRANSACTIONDATE, TRANSACTIONTIME, OPERDATE, OPERTIME, TRANSACTIONACCOUNTID, ",
        "BRANCHCODE, FUNDCODE, SHARETYPE, CURRENCYTYPE, APPLICATIONVOL, APPLICATIONAMOUNT, ",
        "ORIGINAPPLICATIONVOL, ORIGINAPPLICATIONAMOUNT, DISCOUNTRATE, ORIGINDISCOUNTRATE, ",
        "TARGETTAACCOUNTID, TARGETDISTRIBUTORCODE, TARGETTRANSACTIONACCOUNTID, TARGETBRANCHCODE, ",
        "TARGETREGIONCODE, TARGETFUNDCODE, TARGETSHARETYPE, UPLOADDATE, ORIGINALSERIALNO, ",
        "ORIGINALCFMDATE, ORIGINALAPPSHEETNO, ORIGINALAPPDATE, ORIGINALSUBSDATE, INVTP, ",
        "REGIONCODE, DEPOSITACCT, SHARECLASS, VALIDPERIOD, DEFDIVIDENDMETHOD, DIVIDENDRATIO, ",
        "FUTUREBUYDATE, CONTRACTNO, PROTOCOLNO, BEGINDATEOFPERIODICSUBS, ENDDATEOFPERIODICSUBS, ",
        "PROTOCALENDDATE, DATEOFPERIODICSUBS, RATIONTERM, RATIONDATE, SAVEPLANFLAG, REGISTERDATE, ",
        "SPECIFYREDEEMFLAG, REDEMPTIONINADVANCEFLAG, REDEMPTIONDATEINADVANCE, DAYSREDEMPTIONINADVANCE, ",
        "REDEMPTIONREASON, LARGEREDEMPTIONFLAG, FROZENCAUSE, FREEZINGDEADLINE, CHARGE, ",
        "HAVEMATCHQTY, TOTALBACKENDLOAD, DETAILFLAG, SPECIFICATION, FROMTAFLAG, MONEYACCOUNT, ",
        "CENTERNO, NETNO, CHANNELID, PAYCENTERID, CUSTMANAGERID, FINANCINGMANAGERID, ",
        "REFERRAL, REFERRALPROV, REFERRALCITY, REFERRALMOBILE, SALESPROMOTION, OPERID, ",
        "NETADDR, CANCELFLAG, PRESTATUS, PAYSTATUS, STATUS, LAST_STATUS, RISKMATCHING, ",
        "ORDERFLAG, EXCEPTIONALFLAG, OPERWAY, OPERORG, BUSINESSKIND, TRANSACTORCERTTYPE, ",
        "TRANSACTORCERTNO, TRANSACTORNAME, ACCEPTMETHOD, TRANSACTORIDSTR, TRANSACTORNAMESTR, ",
        "PAYTYPE, ORGINCHANNELID, SOURCE, SEATCODE, SECURITIESACCOUNTID, REJECTMSG, ISREEDOM",
        "from APP_TRANS",
        "where DISTRIBUTORCODE = #{distributorcode,jdbcType=CHAR}",
          "and APPSHEETSERIALNO = #{appsheetserialno,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="DISTRIBUTORCODE", property="distributorcode", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="APPSHEETSERIALNO", property="appsheetserialno", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="IODATE", property="iodate", jdbcType=JdbcType.CHAR),
        @Result(column="SNO", property="sno", jdbcType=JdbcType.DECIMAL),
        @Result(column="RETURNMSG", property="returnmsg", jdbcType=JdbcType.VARCHAR),
        @Result(column="RETURNCODE", property="returncode", jdbcType=JdbcType.CHAR),
        @Result(column="TANO", property="tano", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSACTIONCFMDATE", property="transactioncfmdate", jdbcType=JdbcType.CHAR),
        @Result(column="TASERIALNO", property="taserialno", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESSCODE", property="businesscode", jdbcType=JdbcType.CHAR),
        @Result(column="BUSINESSCODE_APP", property="businesscodeApp", jdbcType=JdbcType.CHAR),
        @Result(column="CUSTNO", property="custno", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUSTTP", property="custtp", jdbcType=JdbcType.CHAR),
        @Result(column="CUSTFULLNAME", property="custfullname", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUSTGROUP", property="custgroup", jdbcType=JdbcType.CHAR),
        @Result(column="CUSTCLASS1", property="custclass1", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUSTCLASS2", property="custclass2", jdbcType=JdbcType.VARCHAR),
        @Result(column="TAACCOUNTID", property="taaccountid", jdbcType=JdbcType.CHAR),
        @Result(column="TAACCOUNTID_APP", property="taaccountidApp", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSACTIONDATE", property="transactiondate", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSACTIONTIME", property="transactiontime", jdbcType=JdbcType.CHAR),
        @Result(column="OPERDATE", property="operdate", jdbcType=JdbcType.CHAR),
        @Result(column="OPERTIME", property="opertime", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSACTIONACCOUNTID", property="transactionaccountid", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRANCHCODE", property="branchcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="FUNDCODE", property="fundcode", jdbcType=JdbcType.CHAR),
        @Result(column="SHARETYPE", property="sharetype", jdbcType=JdbcType.CHAR),
        @Result(column="CURRENCYTYPE", property="currencytype", jdbcType=JdbcType.CHAR),
        @Result(column="APPLICATIONVOL", property="applicationvol", jdbcType=JdbcType.DECIMAL),
        @Result(column="APPLICATIONAMOUNT", property="applicationamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORIGINAPPLICATIONVOL", property="originapplicationvol", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORIGINAPPLICATIONAMOUNT", property="originapplicationamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="DISCOUNTRATE", property="discountrate", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORIGINDISCOUNTRATE", property="origindiscountrate", jdbcType=JdbcType.DECIMAL),
        @Result(column="TARGETTAACCOUNTID", property="targettaaccountid", jdbcType=JdbcType.CHAR),
        @Result(column="TARGETDISTRIBUTORCODE", property="targetdistributorcode", jdbcType=JdbcType.CHAR),
        @Result(column="TARGETTRANSACTIONACCOUNTID", property="targettransactionaccountid", jdbcType=JdbcType.VARCHAR),
        @Result(column="TARGETBRANCHCODE", property="targetbranchcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="TARGETREGIONCODE", property="targetregioncode", jdbcType=JdbcType.CHAR),
        @Result(column="TARGETFUNDCODE", property="targetfundcode", jdbcType=JdbcType.CHAR),
        @Result(column="TARGETSHARETYPE", property="targetsharetype", jdbcType=JdbcType.CHAR),
        @Result(column="UPLOADDATE", property="uploaddate", jdbcType=JdbcType.CHAR),
        @Result(column="ORIGINALSERIALNO", property="originalserialno", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORIGINALCFMDATE", property="originalcfmdate", jdbcType=JdbcType.CHAR),
        @Result(column="ORIGINALAPPSHEETNO", property="originalappsheetno", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORIGINALAPPDATE", property="originalappdate", jdbcType=JdbcType.CHAR),
        @Result(column="ORIGINALSUBSDATE", property="originalsubsdate", jdbcType=JdbcType.CHAR),
        @Result(column="INVTP", property="invtp", jdbcType=JdbcType.CHAR),
        @Result(column="REGIONCODE", property="regioncode", jdbcType=JdbcType.CHAR),
        @Result(column="DEPOSITACCT", property="depositacct", jdbcType=JdbcType.VARCHAR),
        @Result(column="SHARECLASS", property="shareclass", jdbcType=JdbcType.CHAR),
        @Result(column="VALIDPERIOD", property="validperiod", jdbcType=JdbcType.DECIMAL),
        @Result(column="DEFDIVIDENDMETHOD", property="defdividendmethod", jdbcType=JdbcType.CHAR),
        @Result(column="DIVIDENDRATIO", property="dividendratio", jdbcType=JdbcType.DECIMAL),
        @Result(column="FUTUREBUYDATE", property="futurebuydate", jdbcType=JdbcType.CHAR),
        @Result(column="CONTRACTNO", property="contractno", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROTOCOLNO", property="protocolno", jdbcType=JdbcType.VARCHAR),
        @Result(column="BEGINDATEOFPERIODICSUBS", property="begindateofperiodicsubs", jdbcType=JdbcType.CHAR),
        @Result(column="ENDDATEOFPERIODICSUBS", property="enddateofperiodicsubs", jdbcType=JdbcType.CHAR),
        @Result(column="PROTOCALENDDATE", property="protocalenddate", jdbcType=JdbcType.CHAR),
        @Result(column="DATEOFPERIODICSUBS", property="dateofperiodicsubs", jdbcType=JdbcType.CHAR),
        @Result(column="RATIONTERM", property="rationterm", jdbcType=JdbcType.VARCHAR),
        @Result(column="RATIONDATE", property="rationdate", jdbcType=JdbcType.DECIMAL),
        @Result(column="SAVEPLANFLAG", property="saveplanflag", jdbcType=JdbcType.CHAR),
        @Result(column="REGISTERDATE", property="registerdate", jdbcType=JdbcType.CHAR),
        @Result(column="SPECIFYREDEEMFLAG", property="specifyredeemflag", jdbcType=JdbcType.CHAR),
        @Result(column="REDEMPTIONINADVANCEFLAG", property="redemptioninadvanceflag", jdbcType=JdbcType.CHAR),
        @Result(column="REDEMPTIONDATEINADVANCE", property="redemptiondateinadvance", jdbcType=JdbcType.CHAR),
        @Result(column="DAYSREDEMPTIONINADVANCE", property="daysredemptioninadvance", jdbcType=JdbcType.DECIMAL),
        @Result(column="REDEMPTIONREASON", property="redemptionreason", jdbcType=JdbcType.CHAR),
        @Result(column="LARGEREDEMPTIONFLAG", property="largeredemptionflag", jdbcType=JdbcType.CHAR),
        @Result(column="FROZENCAUSE", property="frozencause", jdbcType=JdbcType.CHAR),
        @Result(column="FREEZINGDEADLINE", property="freezingdeadline", jdbcType=JdbcType.CHAR),
        @Result(column="CHARGE", property="charge", jdbcType=JdbcType.DECIMAL),
        @Result(column="HAVEMATCHQTY", property="havematchqty", jdbcType=JdbcType.DECIMAL),
        @Result(column="TOTALBACKENDLOAD", property="totalbackendload", jdbcType=JdbcType.DECIMAL),
        @Result(column="DETAILFLAG", property="detailflag", jdbcType=JdbcType.CHAR),
        @Result(column="SPECIFICATION", property="specification", jdbcType=JdbcType.VARCHAR),
        @Result(column="FROMTAFLAG", property="fromtaflag", jdbcType=JdbcType.CHAR),
        @Result(column="MONEYACCOUNT", property="moneyaccount", jdbcType=JdbcType.DECIMAL),
        @Result(column="CENTERNO", property="centerno", jdbcType=JdbcType.VARCHAR),
        @Result(column="NETNO", property="netno", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHANNELID", property="channelid", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAYCENTERID", property="paycenterid", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUSTMANAGERID", property="custmanagerid", jdbcType=JdbcType.VARCHAR),
        @Result(column="FINANCINGMANAGERID", property="financingmanagerid", jdbcType=JdbcType.VARCHAR),
        @Result(column="REFERRAL", property="referral", jdbcType=JdbcType.VARCHAR),
        @Result(column="REFERRALPROV", property="referralprov", jdbcType=JdbcType.VARCHAR),
        @Result(column="REFERRALCITY", property="referralcity", jdbcType=JdbcType.VARCHAR),
        @Result(column="REFERRALMOBILE", property="referralmobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="SALESPROMOTION", property="salespromotion", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPERID", property="operid", jdbcType=JdbcType.VARCHAR),
        @Result(column="NETADDR", property="netaddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="CANCELFLAG", property="cancelflag", jdbcType=JdbcType.CHAR),
        @Result(column="PRESTATUS", property="prestatus", jdbcType=JdbcType.CHAR),
        @Result(column="PAYSTATUS", property="paystatus", jdbcType=JdbcType.CHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="LAST_STATUS", property="lastStatus", jdbcType=JdbcType.CHAR),
        @Result(column="RISKMATCHING", property="riskmatching", jdbcType=JdbcType.CHAR),
        @Result(column="ORDERFLAG", property="orderflag", jdbcType=JdbcType.CHAR),
        @Result(column="EXCEPTIONALFLAG", property="exceptionalflag", jdbcType=JdbcType.CHAR),
        @Result(column="OPERWAY", property="operway", jdbcType=JdbcType.CHAR),
        @Result(column="OPERORG", property="operorg", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESSKIND", property="businesskind", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSACTORCERTTYPE", property="transactorcerttype", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSACTORCERTNO", property="transactorcertno", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSACTORNAME", property="transactorname", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACCEPTMETHOD", property="acceptmethod", jdbcType=JdbcType.CHAR),
        @Result(column="TRANSACTORIDSTR", property="transactoridstr", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSACTORNAMESTR", property="transactornamestr", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAYTYPE", property="paytype", jdbcType=JdbcType.CHAR),
        @Result(column="ORGINCHANNELID", property="orginchannelid", jdbcType=JdbcType.VARCHAR),
        @Result(column="SOURCE", property="source", jdbcType=JdbcType.CHAR),
        @Result(column="SEATCODE", property="seatcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="SECURITIESACCOUNTID", property="securitiesaccountid", jdbcType=JdbcType.VARCHAR),
        @Result(column="REJECTMSG", property="rejectmsg", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISREEDOM", property="isreedom", jdbcType=JdbcType.CHAR)
    })
    kfat selectByPrimaryKey(kfatKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @UpdateProvider(type=kfatSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") kfat record, @Param("example") kfatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @UpdateProvider(type=kfatSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") kfat record, @Param("example") kfatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @UpdateProvider(type=kfatSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(kfat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_TRANS
     *
     * @mbggenerated
     */
    @Update({
        "update APP_TRANS",
        "set IODATE = #{iodate,jdbcType=CHAR},",
          "SNO = #{sno,jdbcType=DECIMAL},",
          "RETURNMSG = #{returnmsg,jdbcType=VARCHAR},",
          "RETURNCODE = #{returncode,jdbcType=CHAR},",
          "TANO = #{tano,jdbcType=CHAR},",
          "TRANSACTIONCFMDATE = #{transactioncfmdate,jdbcType=CHAR},",
          "TASERIALNO = #{taserialno,jdbcType=VARCHAR},",
          "BUSINESSCODE = #{businesscode,jdbcType=CHAR},",
          "BUSINESSCODE_APP = #{businesscodeApp,jdbcType=CHAR},",
          "CUSTNO = #{custno,jdbcType=DECIMAL},",
          "CUSTTP = #{custtp,jdbcType=CHAR},",
          "CUSTFULLNAME = #{custfullname,jdbcType=VARCHAR},",
          "CUSTGROUP = #{custgroup,jdbcType=CHAR},",
          "CUSTCLASS1 = #{custclass1,jdbcType=VARCHAR},",
          "CUSTCLASS2 = #{custclass2,jdbcType=VARCHAR},",
          "TAACCOUNTID = #{taaccountid,jdbcType=CHAR},",
          "TAACCOUNTID_APP = #{taaccountidApp,jdbcType=CHAR},",
          "TRANSACTIONDATE = #{transactiondate,jdbcType=CHAR},",
          "TRANSACTIONTIME = #{transactiontime,jdbcType=CHAR},",
          "OPERDATE = #{operdate,jdbcType=CHAR},",
          "OPERTIME = #{opertime,jdbcType=CHAR},",
          "TRANSACTIONACCOUNTID = #{transactionaccountid,jdbcType=VARCHAR},",
          "BRANCHCODE = #{branchcode,jdbcType=VARCHAR},",
          "FUNDCODE = #{fundcode,jdbcType=CHAR},",
          "SHARETYPE = #{sharetype,jdbcType=CHAR},",
          "CURRENCYTYPE = #{currencytype,jdbcType=CHAR},",
          "APPLICATIONVOL = #{applicationvol,jdbcType=DECIMAL},",
          "APPLICATIONAMOUNT = #{applicationamount,jdbcType=DECIMAL},",
          "ORIGINAPPLICATIONVOL = #{originapplicationvol,jdbcType=DECIMAL},",
          "ORIGINAPPLICATIONAMOUNT = #{originapplicationamount,jdbcType=DECIMAL},",
          "DISCOUNTRATE = #{discountrate,jdbcType=DECIMAL},",
          "ORIGINDISCOUNTRATE = #{origindiscountrate,jdbcType=DECIMAL},",
          "TARGETTAACCOUNTID = #{targettaaccountid,jdbcType=CHAR},",
          "TARGETDISTRIBUTORCODE = #{targetdistributorcode,jdbcType=CHAR},",
          "TARGETTRANSACTIONACCOUNTID = #{targettransactionaccountid,jdbcType=VARCHAR},",
          "TARGETBRANCHCODE = #{targetbranchcode,jdbcType=VARCHAR},",
          "TARGETREGIONCODE = #{targetregioncode,jdbcType=CHAR},",
          "TARGETFUNDCODE = #{targetfundcode,jdbcType=CHAR},",
          "TARGETSHARETYPE = #{targetsharetype,jdbcType=CHAR},",
          "UPLOADDATE = #{uploaddate,jdbcType=CHAR},",
          "ORIGINALSERIALNO = #{originalserialno,jdbcType=VARCHAR},",
          "ORIGINALCFMDATE = #{originalcfmdate,jdbcType=CHAR},",
          "ORIGINALAPPSHEETNO = #{originalappsheetno,jdbcType=VARCHAR},",
          "ORIGINALAPPDATE = #{originalappdate,jdbcType=CHAR},",
          "ORIGINALSUBSDATE = #{originalsubsdate,jdbcType=CHAR},",
          "INVTP = #{invtp,jdbcType=CHAR},",
          "REGIONCODE = #{regioncode,jdbcType=CHAR},",
          "DEPOSITACCT = #{depositacct,jdbcType=VARCHAR},",
          "SHARECLASS = #{shareclass,jdbcType=CHAR},",
          "VALIDPERIOD = #{validperiod,jdbcType=DECIMAL},",
          "DEFDIVIDENDMETHOD = #{defdividendmethod,jdbcType=CHAR},",
          "DIVIDENDRATIO = #{dividendratio,jdbcType=DECIMAL},",
          "FUTUREBUYDATE = #{futurebuydate,jdbcType=CHAR},",
          "CONTRACTNO = #{contractno,jdbcType=VARCHAR},",
          "PROTOCOLNO = #{protocolno,jdbcType=VARCHAR},",
          "BEGINDATEOFPERIODICSUBS = #{begindateofperiodicsubs,jdbcType=CHAR},",
          "ENDDATEOFPERIODICSUBS = #{enddateofperiodicsubs,jdbcType=CHAR},",
          "PROTOCALENDDATE = #{protocalenddate,jdbcType=CHAR},",
          "DATEOFPERIODICSUBS = #{dateofperiodicsubs,jdbcType=CHAR},",
          "RATIONTERM = #{rationterm,jdbcType=VARCHAR},",
          "RATIONDATE = #{rationdate,jdbcType=DECIMAL},",
          "SAVEPLANFLAG = #{saveplanflag,jdbcType=CHAR},",
          "REGISTERDATE = #{registerdate,jdbcType=CHAR},",
          "SPECIFYREDEEMFLAG = #{specifyredeemflag,jdbcType=CHAR},",
          "REDEMPTIONINADVANCEFLAG = #{redemptioninadvanceflag,jdbcType=CHAR},",
          "REDEMPTIONDATEINADVANCE = #{redemptiondateinadvance,jdbcType=CHAR},",
          "DAYSREDEMPTIONINADVANCE = #{daysredemptioninadvance,jdbcType=DECIMAL},",
          "REDEMPTIONREASON = #{redemptionreason,jdbcType=CHAR},",
          "LARGEREDEMPTIONFLAG = #{largeredemptionflag,jdbcType=CHAR},",
          "FROZENCAUSE = #{frozencause,jdbcType=CHAR},",
          "FREEZINGDEADLINE = #{freezingdeadline,jdbcType=CHAR},",
          "CHARGE = #{charge,jdbcType=DECIMAL},",
          "HAVEMATCHQTY = #{havematchqty,jdbcType=DECIMAL},",
          "TOTALBACKENDLOAD = #{totalbackendload,jdbcType=DECIMAL},",
          "DETAILFLAG = #{detailflag,jdbcType=CHAR},",
          "SPECIFICATION = #{specification,jdbcType=VARCHAR},",
          "FROMTAFLAG = #{fromtaflag,jdbcType=CHAR},",
          "MONEYACCOUNT = #{moneyaccount,jdbcType=DECIMAL},",
          "CENTERNO = #{centerno,jdbcType=VARCHAR},",
          "NETNO = #{netno,jdbcType=VARCHAR},",
          "CHANNELID = #{channelid,jdbcType=VARCHAR},",
          "PAYCENTERID = #{paycenterid,jdbcType=VARCHAR},",
          "CUSTMANAGERID = #{custmanagerid,jdbcType=VARCHAR},",
          "FINANCINGMANAGERID = #{financingmanagerid,jdbcType=VARCHAR},",
          "REFERRAL = #{referral,jdbcType=VARCHAR},",
          "REFERRALPROV = #{referralprov,jdbcType=VARCHAR},",
          "REFERRALCITY = #{referralcity,jdbcType=VARCHAR},",
          "REFERRALMOBILE = #{referralmobile,jdbcType=VARCHAR},",
          "SALESPROMOTION = #{salespromotion,jdbcType=VARCHAR},",
          "OPERID = #{operid,jdbcType=VARCHAR},",
          "NETADDR = #{netaddr,jdbcType=VARCHAR},",
          "CANCELFLAG = #{cancelflag,jdbcType=CHAR},",
          "PRESTATUS = #{prestatus,jdbcType=CHAR},",
          "PAYSTATUS = #{paystatus,jdbcType=CHAR},",
          "STATUS = #{status,jdbcType=CHAR},",
          "LAST_STATUS = #{lastStatus,jdbcType=CHAR},",
          "RISKMATCHING = #{riskmatching,jdbcType=CHAR},",
          "ORDERFLAG = #{orderflag,jdbcType=CHAR},",
          "EXCEPTIONALFLAG = #{exceptionalflag,jdbcType=CHAR},",
          "OPERWAY = #{operway,jdbcType=CHAR},",
          "OPERORG = #{operorg,jdbcType=VARCHAR},",
          "BUSINESSKIND = #{businesskind,jdbcType=CHAR},",
          "TRANSACTORCERTTYPE = #{transactorcerttype,jdbcType=CHAR},",
          "TRANSACTORCERTNO = #{transactorcertno,jdbcType=VARCHAR},",
          "TRANSACTORNAME = #{transactorname,jdbcType=VARCHAR},",
          "ACCEPTMETHOD = #{acceptmethod,jdbcType=CHAR},",
          "TRANSACTORIDSTR = #{transactoridstr,jdbcType=VARCHAR},",
          "TRANSACTORNAMESTR = #{transactornamestr,jdbcType=VARCHAR},",
          "PAYTYPE = #{paytype,jdbcType=CHAR},",
          "ORGINCHANNELID = #{orginchannelid,jdbcType=VARCHAR},",
          "SOURCE = #{source,jdbcType=CHAR},",
          "SEATCODE = #{seatcode,jdbcType=VARCHAR},",
          "SECURITIESACCOUNTID = #{securitiesaccountid,jdbcType=VARCHAR},",
          "REJECTMSG = #{rejectmsg,jdbcType=VARCHAR},",
          "ISREEDOM = #{isreedom,jdbcType=CHAR}",
        "where DISTRIBUTORCODE = #{distributorcode,jdbcType=CHAR}",
          "and APPSHEETSERIALNO = #{appsheetserialno,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(kfat record);
}