package org.csnowfox.maven.plugin.example.dao.fund;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface FundCalendarMapper extends org.csnowfox.maven.plugin.example.SqlMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    @SelectProvider(type=FundCalendarSqlProvider.class, method="countByExample")
    int countByExample(FundCalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    @DeleteProvider(type=FundCalendarSqlProvider.class, method="deleteByExample")
    int deleteByExample(FundCalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    @Delete({
        "delete",
        "from FUND_CALENDAR",
        "where 1=1 ",
        "and taid = #{taid,jdbcType=VARCHAR}",
        "and fundcode = #{fundcode,jdbcType=VARCHAR}",
        "and idate = #{idate,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String taid,String fundcode,String idate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    @Insert({
        "insert into FUND_CALENDAR (",
        "taid,fundcode,idate,marketflag,updatetime",
        ")",
        "values (#{taid,jdbcType=VARCHAR}",
        ",#{fundcode,jdbcType=VARCHAR}",
        ",#{idate,jdbcType=VARCHAR}",
        ",#{marketflag,jdbcType=VARCHAR}",
        ",#{updatetime,jdbcType=VARCHAR})"
    })
    int insert(FundCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    @InsertProvider(type=FundCalendarSqlProvider.class, method="insertSelective")
    int insertSelective(FundCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    @SelectProvider(type=FundCalendarSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="taid", property="taid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="fundcode", property="fundcode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="idate", property="idate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="marketflag", property="marketflag", jdbcType=JdbcType.VARCHAR),
        @Result(column="updatetime", property="updatetime", jdbcType=JdbcType.VARCHAR)
    })
    List<FundCalendar> selectByExample(FundCalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    @Select({
        "select",
        " taid",
        ", fundcode",
        ", idate",
        ", marketflag",
        ", updatetime",
        "from FUND_CALENDAR",
        "where 1=1 ",
        "and taid = #{taid,jdbcType=VARCHAR}",
        "and fundcode = #{fundcode,jdbcType=VARCHAR}",
        "and idate = #{idate,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="taid", property="taid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="fundcode", property="fundcode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="idate", property="idate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="marketflag", property="marketflag", jdbcType=JdbcType.VARCHAR),
        @Result(column="updatetime", property="updatetime", jdbcType=JdbcType.VARCHAR)
    })
    FundCalendar selectByPrimaryKey(String taid,String fundcode,String idate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    @UpdateProvider(type=FundCalendarSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") FundCalendar record, @Param("example") FundCalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    @UpdateProvider(type=FundCalendarSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") FundCalendar record, @Param("example") FundCalendarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    @UpdateProvider(type=FundCalendarSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(FundCalendar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    @Update({
        "update FundCalendar",
        "set ",
        "marketflag = #{marketflag,jdbcType=VARCHAR}",
        ",updatetime = #{updatetime,jdbcType=VARCHAR}",
        "where 1=1 ",
        "and taid = #{taid,jdbcType=VARCHAR}",
        "and fundcode = #{fundcode,jdbcType=VARCHAR}",
        "and idate = #{idate,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(FundCalendar record);
}