package org.csnowfox.maven.plugin.example.dao.fund;

import java.util.ArrayList;
import java.util.List;

public class FundCalendarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public FundCalendarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FUND_CALENDAR
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaidIsNull() {
            addCriterion("taid is null");
            return (Criteria) this;
        }

        public Criteria andTaidIsNotNull() {
            addCriterion("taid is not null");
            return (Criteria) this;
        }

        public Criteria andTaidEqualTo(String value) {
            addCriterion("taid =", value, "taid");
            return (Criteria) this;
        }

        public Criteria andTaidNotEqualTo(String value) {
            addCriterion("taid <>", value, "taid");
            return (Criteria) this;
        }

        public Criteria andTaidGreaterThan(String value) {
            addCriterion("taid >", value, "taid");
            return (Criteria) this;
        }

        public Criteria andTaidGreaterThanOrEqualTo(String value) {
            addCriterion("taid >=", value, "taid");
            return (Criteria) this;
        }

        public Criteria andTaidLessThan(String value) {
            addCriterion("taid <", value, "taid");
            return (Criteria) this;
        }

        public Criteria andTaidLessThanOrEqualTo(String value) {
            addCriterion("taid <=", value, "taid");
            return (Criteria) this;
        }

        public Criteria andTaidLike(String value) {
            addCriterion("taid like", value, "taid");
            return (Criteria) this;
        }

        public Criteria andTaidNotLike(String value) {
            addCriterion("taid not like", value, "taid");
            return (Criteria) this;
        }

        public Criteria andTaidIn(List<String> values) {
            addCriterion("taid in", values, "taid");
            return (Criteria) this;
        }

        public Criteria andTaidNotIn(List<String> values) {
            addCriterion("taid not in", values, "taid");
            return (Criteria) this;
        }

        public Criteria andTaidBetween(String value1, String value2) {
            addCriterion("taid between", value1, value2, "taid");
            return (Criteria) this;
        }

        public Criteria andTaidNotBetween(String value1, String value2) {
            addCriterion("taid not between", value1, value2, "taid");
            return (Criteria) this;
        }

        public Criteria andFundcodeIsNull() {
            addCriterion("fundcode is null");
            return (Criteria) this;
        }

        public Criteria andFundcodeIsNotNull() {
            addCriterion("fundcode is not null");
            return (Criteria) this;
        }

        public Criteria andFundcodeEqualTo(String value) {
            addCriterion("fundcode =", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeNotEqualTo(String value) {
            addCriterion("fundcode <>", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeGreaterThan(String value) {
            addCriterion("fundcode >", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeGreaterThanOrEqualTo(String value) {
            addCriterion("fundcode >=", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeLessThan(String value) {
            addCriterion("fundcode <", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeLessThanOrEqualTo(String value) {
            addCriterion("fundcode <=", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeLike(String value) {
            addCriterion("fundcode like", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeNotLike(String value) {
            addCriterion("fundcode not like", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeIn(List<String> values) {
            addCriterion("fundcode in", values, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeNotIn(List<String> values) {
            addCriterion("fundcode not in", values, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeBetween(String value1, String value2) {
            addCriterion("fundcode between", value1, value2, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeNotBetween(String value1, String value2) {
            addCriterion("fundcode not between", value1, value2, "fundcode");
            return (Criteria) this;
        }

        public Criteria andIdateIsNull() {
            addCriterion("idate is null");
            return (Criteria) this;
        }

        public Criteria andIdateIsNotNull() {
            addCriterion("idate is not null");
            return (Criteria) this;
        }

        public Criteria andIdateEqualTo(String value) {
            addCriterion("idate =", value, "idate");
            return (Criteria) this;
        }

        public Criteria andIdateNotEqualTo(String value) {
            addCriterion("idate <>", value, "idate");
            return (Criteria) this;
        }

        public Criteria andIdateGreaterThan(String value) {
            addCriterion("idate >", value, "idate");
            return (Criteria) this;
        }

        public Criteria andIdateGreaterThanOrEqualTo(String value) {
            addCriterion("idate >=", value, "idate");
            return (Criteria) this;
        }

        public Criteria andIdateLessThan(String value) {
            addCriterion("idate <", value, "idate");
            return (Criteria) this;
        }

        public Criteria andIdateLessThanOrEqualTo(String value) {
            addCriterion("idate <=", value, "idate");
            return (Criteria) this;
        }

        public Criteria andIdateLike(String value) {
            addCriterion("idate like", value, "idate");
            return (Criteria) this;
        }

        public Criteria andIdateNotLike(String value) {
            addCriterion("idate not like", value, "idate");
            return (Criteria) this;
        }

        public Criteria andIdateIn(List<String> values) {
            addCriterion("idate in", values, "idate");
            return (Criteria) this;
        }

        public Criteria andIdateNotIn(List<String> values) {
            addCriterion("idate not in", values, "idate");
            return (Criteria) this;
        }

        public Criteria andIdateBetween(String value1, String value2) {
            addCriterion("idate between", value1, value2, "idate");
            return (Criteria) this;
        }

        public Criteria andIdateNotBetween(String value1, String value2) {
            addCriterion("idate not between", value1, value2, "idate");
            return (Criteria) this;
        }

        public Criteria andMarketflagIsNull() {
            addCriterion("marketflag is null");
            return (Criteria) this;
        }

        public Criteria andMarketflagIsNotNull() {
            addCriterion("marketflag is not null");
            return (Criteria) this;
        }

        public Criteria andMarketflagEqualTo(String value) {
            addCriterion("marketflag =", value, "marketflag");
            return (Criteria) this;
        }

        public Criteria andMarketflagNotEqualTo(String value) {
            addCriterion("marketflag <>", value, "marketflag");
            return (Criteria) this;
        }

        public Criteria andMarketflagGreaterThan(String value) {
            addCriterion("marketflag >", value, "marketflag");
            return (Criteria) this;
        }

        public Criteria andMarketflagGreaterThanOrEqualTo(String value) {
            addCriterion("marketflag >=", value, "marketflag");
            return (Criteria) this;
        }

        public Criteria andMarketflagLessThan(String value) {
            addCriterion("marketflag <", value, "marketflag");
            return (Criteria) this;
        }

        public Criteria andMarketflagLessThanOrEqualTo(String value) {
            addCriterion("marketflag <=", value, "marketflag");
            return (Criteria) this;
        }

        public Criteria andMarketflagLike(String value) {
            addCriterion("marketflag like", value, "marketflag");
            return (Criteria) this;
        }

        public Criteria andMarketflagNotLike(String value) {
            addCriterion("marketflag not like", value, "marketflag");
            return (Criteria) this;
        }

        public Criteria andMarketflagIn(List<String> values) {
            addCriterion("marketflag in", values, "marketflag");
            return (Criteria) this;
        }

        public Criteria andMarketflagNotIn(List<String> values) {
            addCriterion("marketflag not in", values, "marketflag");
            return (Criteria) this;
        }

        public Criteria andMarketflagBetween(String value1, String value2) {
            addCriterion("marketflag between", value1, value2, "marketflag");
            return (Criteria) this;
        }

        public Criteria andMarketflagNotBetween(String value1, String value2) {
            addCriterion("marketflag not between", value1, value2, "marketflag");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(String value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(String value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(String value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(String value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(String value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLike(String value) {
            addCriterion("updatetime like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotLike(String value) {
            addCriterion("updatetime not like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<String> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<String> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(String value1, String value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(String value1, String value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }


    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b3_solo_user
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b3_solo_user
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}