package org.csnowfox.maven.plugin.example.dao.fund;

public class FundCalendar {

    /**
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    private String taid;

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    public String getTaid() {
        return taid;
    }

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    public void setTaid(String taid) {
        this.taid = taid == null ? null : taid.trim();
    }

    /**
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    private String fundcode;

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    public String getFundcode() {
        return fundcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    public void setFundcode(String fundcode) {
        this.fundcode = fundcode == null ? null : fundcode.trim();
    }

    /**
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    private String idate;

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    public String getIdate() {
        return idate;
    }

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    public void setIdate(String idate) {
        this.idate = idate == null ? null : idate.trim();
    }

    /**
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    private String marketflag;

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    public String getMarketflag() {
        return marketflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    public void setMarketflag(String marketflag) {
        this.marketflag = marketflag == null ? null : marketflag.trim();
    }

    /**
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FundCalendar other = (FundCalendar) that;
        return true
            && (this.getTaid() == null ? other.getTaid() == null : this.getTaid().equals(other.getTaid()))
            && (this.getFundcode() == null ? other.getFundcode() == null : this.getFundcode().equals(other.getFundcode()))
            && (this.getIdate() == null ? other.getIdate() == null : this.getIdate().equals(other.getIdate()))
            && (this.getMarketflag() == null ? other.getMarketflag() == null : this.getMarketflag().equals(other.getMarketflag()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTaid() == null) ? 0 : getTaid().hashCode());
        result = prime * result + ((getFundcode() == null) ? 0 : getFundcode().hashCode());
        result = prime * result + ((getIdate() == null) ? 0 : getIdate().hashCode());
        result = prime * result + ((getMarketflag() == null) ? 0 : getMarketflag().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }


}