package ${project_package};

public class ${entity_class} {

    <#list class_columns as col>
    /**
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    private ${col.clazz} ${col.name};

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    public ${col.clazz} get${col.upcaseCamelName}() {
        return ${col.name};
    }

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    public void set${col.upcaseCamelName}(${col.clazz} ${col.name}) {
        this.${col.name} = ${col.name} == null ? null : ${col.name}.trim();
    }

    </#list>


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ${entity_class} other = (${entity_class}) that;
        return true
        <#list class_columns as col>
            && (this.get${col.upcaseCamelName}() == null ? other.get${col.upcaseCamelName}() == null : this.get${col.upcaseCamelName}().equals(other.get${col.upcaseCamelName}()))
        </#list>
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b3_solo_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        <#list class_columns as col>
        result = prime * result + ((get${col.upcaseCamelName}() == null) ? 0 : get${col.upcaseCamelName}().hashCode());
        </#list>
        return result;
    }


}