/*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package ${project_package};

/**
 * Created by mydel2mybatis tool
 * @description ${entity_comment}
 */
public class ${entity_class} {

    <#list class_columns as col>
    /**
     * This field was generated by MyBatis Generator.
     * @description ${col.comment}
     * @mbggenerated
     */
    private ${col.clazz} ${col.name};

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    public ${col.clazz} get${col.upcaseCamelName}() {
        return ${col.name};
    }

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    public void set${col.upcaseCamelName}(${col.clazz} ${col.name}) {
        this.${col.name} = ${col.name} == null ? null : ${col.name}.trim();
    }

    </#list>


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ${entity_class} other = (${entity_class}) that;
        return true
        <#list class_columns as col>
            && (this.get${col.upcaseCamelName}() == null ? other.get${col.upcaseCamelName}() == null : this.get${col.upcaseCamelName}().equals(other.get${col.upcaseCamelName}()))
        </#list>
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        <#list class_columns as col>
        result = prime * result + ((get${col.upcaseCamelName}() == null) ? 0 : get${col.upcaseCamelName}().hashCode());
        </#list>
        return result;
    }


}